/* Generated by scripts/generate-puzzle-masks.mjs — do not edit by hand. */
export const PUZZLE_WIDTH = 450;
export const PUZZLE_HEIGHT = 600;
export const PUZZLE_COLS = 5;
export const PUZZLE_ROWS = 7;
export const PIECE_COUNT = 35;

export type PieceBBox = { x: number; y: number; w: number; h: number };

export type PieceMeta = {
  id: number;
  file: string;
  row: number;
  col: number;
  bbox: PieceBBox;
};

export const PIECES: PieceMeta[] = [
  {
    "id": 1,
    "file": "piece-01.svg",
    "row": 0,
    "col": 0,
    "bbox": {
      "x": 0,
      "y": 0,
      "w": 111,
      "h": 106
    }
  },
  {
    "id": 2,
    "file": "piece-02.svg",
    "row": 0,
    "col": 1,
    "bbox": {
      "x": 87,
      "y": 0,
      "w": 97,
      "h": 106
    }
  },
  {
    "id": 3,
    "file": "piece-03.svg",
    "row": 0,
    "col": 2,
    "bbox": {
      "x": 160,
      "y": 0,
      "w": 130,
      "h": 105
    }
  },
  {
    "id": 4,
    "file": "piece-04.svg",
    "row": 0,
    "col": 3,
    "bbox": {
      "x": 266,
      "y": 0,
      "w": 113,
      "h": 89
    }
  },
  {
    "id": 5,
    "file": "piece-05.svg",
    "row": 0,
    "col": 4,
    "bbox": {
      "x": 357,
      "y": 0,
      "w": 93,
      "h": 104
    }
  },
  {
    "id": 6,
    "file": "piece-06.svg",
    "row": 1,
    "col": 0,
    "bbox": {
      "x": 0,
      "y": 83,
      "w": 93,
      "h": 108
    }
  },
  {
    "id": 7,
    "file": "piece-07.svg",
    "row": 1,
    "col": 1,
    "bbox": {
      "x": 69,
      "y": 83,
      "w": 114,
      "h": 92
    }
  },
  {
    "id": 8,
    "file": "piece-08.svg",
    "row": 1,
    "col": 2,
    "bbox": {
      "x": 161,
      "y": 82,
      "w": 129,
      "h": 93
    }
  },
  {
    "id": 9,
    "file": "piece-09.svg",
    "row": 1,
    "col": 3,
    "bbox": {
      "x": 267,
      "y": 66,
      "w": 96,
      "h": 125
    }
  },
  {
    "id": 10,
    "file": "piece-10.svg",
    "row": 1,
    "col": 4,
    "bbox": {
      "x": 340,
      "y": 82,
      "w": 110,
      "h": 91
    }
  },
  {
    "id": 11,
    "file": "piece-11.svg",
    "row": 2,
    "col": 0,
    "bbox": {
      "x": 0,
      "y": 169,
      "w": 110,
      "h": 91
    }
  },
  {
    "id": 12,
    "file": "piece-12.svg",
    "row": 2,
    "col": 1,
    "bbox": {
      "x": 87,
      "y": 152,
      "w": 112,
      "h": 109
    }
  },
  {
    "id": 13,
    "file": "piece-13.svg",
    "row": 2,
    "col": 2,
    "bbox": {
      "x": 176,
      "y": 152,
      "w": 115,
      "h": 125
    }
  },
  {
    "id": 14,
    "file": "piece-14.svg",
    "row": 2,
    "col": 3,
    "bbox": {
      "x": 267,
      "y": 168,
      "w": 97,
      "h": 109
    }
  },
  {
    "id": 15,
    "file": "piece-15.svg",
    "row": 2,
    "col": 4,
    "bbox": {
      "x": 340,
      "y": 151,
      "w": 110,
      "h": 109
    }
  },
  {
    "id": 16,
    "file": "piece-16.svg",
    "row": 3,
    "col": 0,
    "bbox": {
      "x": 0,
      "y": 238,
      "w": 109,
      "h": 124
    }
  },
  {
    "id": 17,
    "file": "piece-17.svg",
    "row": 3,
    "col": 1,
    "bbox": {
      "x": 86,
      "y": 239,
      "w": 115,
      "h": 124
    }
  },
  {
    "id": 18,
    "file": "piece-18.svg",
    "row": 3,
    "col": 2,
    "bbox": {
      "x": 177,
      "y": 254,
      "w": 114,
      "h": 110
    }
  },
  {
    "id": 19,
    "file": "piece-19.svg",
    "row": 3,
    "col": 3,
    "bbox": {
      "x": 267,
      "y": 254,
      "w": 114,
      "h": 91
    }
  },
  {
    "id": 20,
    "file": "piece-20.svg",
    "row": 3,
    "col": 4,
    "bbox": {
      "x": 358,
      "y": 238,
      "w": 92,
      "h": 109
    }
  },
  {
    "id": 21,
    "file": "piece-21.svg",
    "row": 4,
    "col": 0,
    "bbox": {
      "x": 0,
      "y": 339,
      "w": 110,
      "h": 93
    }
  },
  {
    "id": 22,
    "file": "piece-22.svg",
    "row": 4,
    "col": 1,
    "bbox": {
      "x": 87,
      "y": 340,
      "w": 97,
      "h": 107
    }
  },
  {
    "id": 23,
    "file": "piece-23.svg",
    "row": 4,
    "col": 2,
    "bbox": {
      "x": 160,
      "y": 341,
      "w": 113,
      "h": 90
    }
  },
  {
    "id": 24,
    "file": "piece-24.svg",
    "row": 4,
    "col": 3,
    "bbox": {
      "x": 249,
      "y": 322,
      "w": 114,
      "h": 110
    }
  },
  {
    "id": 25,
    "file": "piece-25.svg",
    "row": 4,
    "col": 4,
    "bbox": {
      "x": 340,
      "y": 325,
      "w": 110,
      "h": 107
    }
  },
  {
    "id": 26,
    "file": "piece-26.svg",
    "row": 5,
    "col": 0,
    "bbox": {
      "x": 0,
      "y": 410,
      "w": 111,
      "h": 123
    }
  },
  {
    "id": 27,
    "file": "piece-27.svg",
    "row": 5,
    "col": 1,
    "bbox": {
      "x": 87,
      "y": 425,
      "w": 96,
      "h": 108
    }
  },
  {
    "id": 28,
    "file": "piece-28.svg",
    "row": 5,
    "col": 2,
    "bbox": {
      "x": 160,
      "y": 408,
      "w": 113,
      "h": 109
    }
  },
  {
    "id": 29,
    "file": "piece-29.svg",
    "row": 5,
    "col": 3,
    "bbox": {
      "x": 249,
      "y": 408,
      "w": 114,
      "h": 109
    }
  },
  {
    "id": 30,
    "file": "piece-30.svg",
    "row": 5,
    "col": 4,
    "bbox": {
      "x": 338,
      "y": 411,
      "w": 112,
      "h": 107
    }
  },
  {
    "id": 31,
    "file": "piece-31.svg",
    "row": 6,
    "col": 0,
    "bbox": {
      "x": 0,
      "y": 511,
      "w": 93,
      "h": 89
    }
  },
  {
    "id": 32,
    "file": "piece-32.svg",
    "row": 6,
    "col": 1,
    "bbox": {
      "x": 68,
      "y": 511,
      "w": 133,
      "h": 89
    }
  },
  {
    "id": 33,
    "file": "piece-33.svg",
    "row": 6,
    "col": 2,
    "bbox": {
      "x": 177,
      "y": 493,
      "w": 115,
      "h": 107
    }
  },
  {
    "id": 34,
    "file": "piece-34.svg",
    "row": 6,
    "col": 3,
    "bbox": {
      "x": 267,
      "y": 494,
      "w": 96,
      "h": 106
    }
  },
  {
    "id": 35,
    "file": "piece-35.svg",
    "row": 6,
    "col": 4,
    "bbox": {
      "x": 339,
      "y": 496,
      "w": 111,
      "h": 104
    }
  }
];
