/** @type {import('../game/themeSpec').ThemeSpec[]} */
export const STATIC_THEMES = [
  {
    bookId: 'lotr',
    title: 'The Lord of the Rings',
    author: 'J.R.R. Tolkien',
    tagline: 'One guess to rule them all',
    accent: '#b08fce',
    schemaVersion: 1,
    words: [
      'FRODO', 'SHIRE', 'ROHAN', 'ARWEN', 'GIMLI', 'EOWYN', 'STING', 'MERRY',
      'BILBO', 'SMAUG', 'EOMER', 'GRIMA', 'WARGS', 'BEORN', 'BALIN', 'GLOIN',
      'BIFUR', 'TOOKS', 'SMIAL', 'VALAR', 'ITHIL', 'HARAD', 'UMBAR', 'ARNOR',
      'MUMAK', 'ELVEN',
    ],
    backdrop: {
      preset: 'shire-hills',
      skyGradient: ['#3a324f 0%', '#2a2438 38%', '#4a425c 70%', '#c9d4b8 100%'],
      silhouetteColor: '#5b4e8c',
      overlayEffect: 'none',
      overlayColor: '#fff6d5',
    },
  },
  {
    bookId: 'harry-potter',
    title: 'Harry Potter',
    author: 'J.K. Rowling',
    tagline: 'Wingardium Guessiosa',
    accent: '#8b3a3a',
    schemaVersion: 1,
    words: [
      'HARRY', 'SNAPE', 'DOBBY', 'DRACO', 'GINNY', 'REMUS', 'TONKS', 'MOODY',
      'FLEUR', 'LUPIN', 'FILCH', 'HOOCH', 'GAUNT', 'ACCIO', 'LUMOS', 'SQUIB',
      'GOYLE', 'MOONY', 'ALBUS', 'FROGS', 'KNUTS', 'NEWTS', 'BELLA', 'PADMA',
      'WINKY', 'FELIX', 'VEELA', 'FUDGE', 'JAMES', 'MOLLY',
    ],
    backdrop: {
      preset: 'castle-towers',
      skyGradient: ['#3a324f 0%', '#f0e6d8 40%', '#e4d0c4 72%', '#d4b8a8 100%'],
      silhouetteColor: '#3d2a2a',
      overlayEffect: 'mist',
      overlayColor: '#b08fce',
    },
  },
  {
    bookId: 'hunger-games',
    title: 'The Hunger Games',
    author: 'Suzanne Collins',
    tagline: 'May the odds be ever in your favor',
    accent: '#5b4e8c',
    schemaVersion: 1,
    words: [
      'PEETA', 'CINNA', 'CLOVE', 'PANEM', 'EFFIE', 'ARENA', 'BREAD', 'ANNIE',
      'BOGGS', 'VENIA', 'QUELL', 'MUTTS', 'COVEY', 'CHAFF', 'MADGE', 'DELLY',
      'CASCA', 'CRANE', 'BAKER', 'BERRY', 'ROSES', 'SONGS',
    ],
    backdrop: {
      preset: 'treeline',
      skyGradient: ['#3a324f 0%', '#2a2438 42%', '#e5e0d0 75%', '#d2d8c4 100%'],
      silhouetteColor: '#9a78c0',
      overlayEffect: 'fireflies',
      overlayColor: '#b08fce',
    },
  },
  {
    bookId: 'it',
    title: 'IT',
    author: 'Stephen King',
    tagline: 'We all float down here',
    accent: '#8b3a3a',
    schemaVersion: 1,
    words: [
      'DERRY', 'CLOWN', 'FLOAT', 'SEWER', 'EDDIE', 'BILLY', 'MARSH', 'HENRY',
      'BELCH', 'LEPER', 'MUMMY', 'BOATS', 'PAPER', 'DRAIN', 'GRATE', 'BIKES',
      'CLUBS', 'WORKS', 'SLIME', 'PIPES', 'PHOTO', 'FEARS',
    ],
    backdrop: {
      preset: 'city-skyline',
      skyGradient: ['#f7f2ea 0%', '#e8d4d0 40%', '#d4b8b4 70%', '#c4a09a 100%'],
      silhouetteColor: '#3a2a2a',
      overlayEffect: 'mist',
      overlayColor: '#8b3a3a',
    },
  },
]
