import type { DiscoverBook } from "./types";

const cover = (isbn: string) =>
  `https://covers.openlibrary.org/b/isbn/${isbn}-L.jpg`;

/** Open Library cover id when ISBN lookup is blank / mis-mapped. */
const coverId = (id: number) =>
  `https://covers.openlibrary.org/b/id/${id}-L.jpg`;

/** ~50 fiction + ~20 nonfiction additions for Discover. */
export const EXPANSION_BOOKS: DiscoverBook[] = [
  // —— Romance ——
  {
    id: "beach-read",
    title: "Beach Read",
    author: "Emily Henry",
    cover: cover("9781984806734"),
    color: "#3a6b7a",
    description:
      "Romance writer January Andrews and literary novelist Gus Everett are opposites stuck writing next door for the summer. They strike a deal to swap genres—and accidentally start falling for each other.",
    genres: ["Romance", "Contemporary"],
    averageRating: 4.15,
    pageCount: 361,
    readLifeReaders: 72000,
    reviewCount: 28000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "trending",
    recommendationReason: "Readers who like witty rom-coms loved this.",
  },
  {
    id: "people-vacation",
    title: "People We Meet on Vacation",
    author: "Emily Henry",
    cover: cover("9781984806758"),
    color: "#5a7a8a",
    description:
      "Poppy and Alex have taken one chaotic vacation together every summer—until a falling-out ends the tradition. When Poppy needs a reset, she asks Alex for one last trip to figure out what went wrong.",
    genres: ["Romance", "Contemporary"],
    averageRating: 4.2,
    pageCount: 364,
    readLifeReaders: 68000,
    reviewCount: 25000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "trending",
  },
  {
    id: "book-lovers",
    title: "Book Lovers",
    author: "Emily Henry",
    cover: cover("9780593334836"),
    color: "#8a3a4a",
    description:
      "Literary agent Nora Stephens is allergic to small-town charm—until a bookish trip with her sister puts her in the orbit of brooding editor Charlie Lastra, and neither can stick to the script.",
    genres: ["Romance", "Contemporary"],
    averageRating: 4.25,
    pageCount: 377,
    readLifeReaders: 64000,
    reviewCount: 22000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "for-you",
  },
  {
    id: "funny-story",
    title: "Funny Story",
    author: "Emily Henry",
    cover: cover("9780593441282"),
    color: "#6b8a5a",
    description:
      "Daphne’s fiancé leaves her for his childhood best friend—so she moves in with Miles, the dumped best friend she barely knows. Fake dating and a tiny Michigan town make things messier (and sweeter) than planned.",
    genres: ["Romance", "Contemporary"],
    averageRating: 4.35,
    pageCount: 395,
    readLifeReaders: 58000,
    reviewCount: 19000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "trending",
  },
  {
    id: "love-hypothesis",
    title: "The Love Hypothesis",
    author: "Ali Hazelwood",
    cover: cover("9780593336823"),
    color: "#c45a6a",
    description:
      "PhD candidate Olive Smith needs a fake boyfriend to convince her best friend she’s moved on. Enter Adam Carlsen, the notoriously intimidating professor who agrees to play along—until the experiment gets very real.",
    genres: ["Romance", "STEM"],
    averageRating: 4.1,
    pageCount: 384,
    readLifeReaders: 91000,
    reviewCount: 41000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "trending",
  },
  {
    id: "red-white-royal",
    title: "Red, White & Royal Blue",
    author: "Casey McQuiston",
    cover: cover("9781250316776"),
    color: "#2a4a8a",
    description:
      "The First Son of the United States and the Prince of Wales are forced into a PR friendship after a tabloid-worthy clash—then emails, secrets, and a very public romance rewrite both their futures.",
    genres: ["Romance", "LGBTQ+", "Contemporary"],
    averageRating: 4.3,
    pageCount: 421,
    readLifeReaders: 76000,
    reviewCount: 33000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "for-you",
  },
  {
    id: "seven-year-slip",
    title: "The Seven Year Slip",
    author: "Ashley Poston",
    cover: cover("9780593543764"),
    color: "#8a5a7a",
    description:
      "Clementine’s inherited apartment sometimes slips through time. When she meets a stranger from seven years in the past, love, grief, and second chances collide across years she isn’t ready to face.",
    genres: ["Romance", "Magical Realism"],
    averageRating: 4.2,
    pageCount: 336,
    readLifeReaders: 24000,
    reviewCount: 7800,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "hidden-gems",
  },

  // —— Thriller / Mystery ——
  {
    id: "gone-girl",
    title: "Gone Girl",
    author: "Gillian Flynn",
    cover: cover("9780307588371"),
    color: "#3a2a2a",
    description:
      "On their fifth anniversary, Amy Dunne disappears. Nick becomes the media’s favorite suspect—and Amy’s diary suggests a marriage far darker than anyone knew. A razor-sharp portrait of marriage, media, and lies.",
    genres: ["Thriller", "Mystery"],
    averageRating: 4.05,
    pageCount: 415,
    readLifeReaders: 98000,
    reviewCount: 48000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "trending",
  },
  {
    id: "verity",
    title: "Verity",
    author: "Colleen Hoover",
    cover: cover("9781538724736"),
    color: "#5a2a3a",
    description:
      "Struggling writer Lowen Ashleigh is hired to finish a bestselling author’s unfinished series after a terrible accident. In the author’s house she finds an unfinished autobiography that may be confession—or a trap.",
    genres: ["Thriller", "Romance"],
    averageRating: 4.3,
    pageCount: 336,
    readLifeReaders: 120000,
    reviewCount: 61000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "trending",
  },
  {
    id: "guest-list",
    title: "The Guest List",
    author: "Lucy Foley",
    cover: cover("9780062868930"),
    color: "#2a3a4a",
    description:
      "A glamorous wedding on a remote Irish island. Old friends, new money, and buried grudges. Before the night is over, someone will be dead—and everyone has a motive.",
    genres: ["Mystery", "Thriller"],
    averageRating: 3.8,
    pageCount: 319,
    readLifeReaders: 52000,
    reviewCount: 21000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "mood",
  },
  {
    id: "maid",
    title: "The Maid",
    author: "Nita Prose",
    cover: cover("9780593356159"),
    color: "#6a8a9a",
    description:
      "Molly Gray loves the clean order of hotel rooms. When she finds a famous guest dead in the penthouse, her quirky honesty makes her the perfect suspect—and the only person who can clear her name.",
    genres: ["Mystery", "Cozy"],
    averageRating: 3.9,
    pageCount: 304,
    readLifeReaders: 41000,
    reviewCount: 15000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "outside",
  },
  {
    id: "last-thing",
    title: "The Last Thing He Told Me",
    author: "Laura Dave",
    cover: cover("9781501171345"),
    color: "#4a5a6a",
    description:
      "Hannah gets a cryptic note from her husband—“Protect her”—before he vanishes. Bonding with her hostile stepdaughter, she digs into a past that was never what she believed.",
    genres: ["Mystery", "Thriller"],
    averageRating: 3.85,
    pageCount: 320,
    readLifeReaders: 47000,
    reviewCount: 17000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "mood",
  },
  {
    id: "sharp-objects",
    title: "Sharp Objects",
    author: "Gillian Flynn",
    cover: coverId(167973),
    color: "#5a3a3a",
    description:
      "Reporter Camille Preaker returns to her hometown to cover the murders of two girls—and confronts the poisonous family she fled. A gothic, lacerating thriller about memory and motherhood.",
    genres: ["Thriller", "Mystery"],
    averageRating: 4.0,
    pageCount: 254,
    readLifeReaders: 43000,
    reviewCount: 16000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "outside",
  },

  // —— Horror ——
  {
    id: "only-good-indians",
    title: "The Only Good Indians",
    author: "Stephen Graham Jones",
    cover: cover("9781982136451"),
    color: "#2a3a2a",
    description:
      "Four American Indian men are haunted by a careless act of violence from their youth. A relentless, inventive horror novel about guilt, community, and the past that won’t stay buried.",
    genres: ["Horror", "Literary"],
    averageRating: 3.7,
    pageCount: 310,
    readLifeReaders: 18000,
    reviewCount: 6200,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "hidden-gems",
  },
  {
    id: "haunting-hill",
    title: "The Haunting of Hill House",
    author: "Shirley Jackson",
    cover: cover("9780143039983"),
    color: "#3a3a4a",
    description:
      "Dr. Montague invites strangers to study Hill House, a mansion that seems to hate the living. Eleanor Vance arrives seeking belonging—and finds something that knows her better than she knows herself.",
    genres: ["Horror", "Gothic", "Classic"],
    averageRating: 3.85,
    pageCount: 182,
    readLifeReaders: 36000,
    reviewCount: 14000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "outside",
  },
  {
    id: "blackened-teeth",
    title: "Nothing but Blackened Teeth",
    author: "Cassandra Khaw",
    cover: coverId(10723430),
    color: "#4a2a3a",
    description:
      "A group of friends gathers in a haunted Heian-era mansion for a wedding that becomes a waking nightmare. Lush, gruesome, and ferociously stylish folk-horror.",
    genres: ["Horror", "Novella"],
    averageRating: 3.2,
    pageCount: 128,
    readLifeReaders: 6200,
    reviewCount: 2100,
    formats: ["Physical", "Ebook"],
    discoveryCategory: "hidden-gems",
  },

  // —— Sci-Fi ——
  {
    id: "dune",
    title: "Dune",
    author: "Frank Herbert",
    cover: cover("9780441172719"),
    color: "#8a6a3a",
    description:
      "Paul Atreides arrives on the desert planet Arrakis, sole source of the spice melange. Betrayal, prophecy, and ecology collide as he walks a path that could remake an empire—and himself.",
    genres: ["Sci-Fi", "Classic"],
    averageRating: 4.25,
    pageCount: 688,
    readLifeReaders: 89000,
    reviewCount: 38000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "for-you",
  },
  {
    id: "three-body",
    title: "The Three-Body Problem",
    author: "Cixin Liu",
    cover: cover("9780765382030"),
    color: "#1a2a4a",
    description:
      "During China’s Cultural Revolution, a secret military project sends signals into space. Decades later, a game and a physics mystery hint that Earth has been noticed—and that contact may not be salvation.",
    genres: ["Sci-Fi"],
    averageRating: 4.05,
    pageCount: 400,
    readLifeReaders: 54000,
    reviewCount: 19000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "outside",
  },
  {
    id: "martian",
    title: "The Martian",
    author: "Andy Weir",
    cover: cover("9780553418026"),
    color: "#a05a2a",
    description:
      "Astronaut Mark Watney is left for dead on Mars. Armed with botany, sarcasm, and duct tape ingenuity, he must science his way to survival while Earth races to bring him home.",
    genres: ["Sci-Fi", "Adventure"],
    averageRating: 4.4,
    pageCount: 387,
    readLifeReaders: 87000,
    reviewCount: 36000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "for-you",
  },
  {
    id: "klara-sun",
    title: "Klara and the Sun",
    author: "Kazuo Ishiguro",
    cover: cover("9780593318171"),
    color: "#7a8a9a",
    description:
      "Klara, an Artificial Friend with unusual observational gifts, watches the world from a shop window—until she is chosen by a girl whose future depends on love, class, and what it means to be human.",
    genres: ["Literary", "Sci-Fi"],
    averageRating: 3.9,
    pageCount: 303,
    readLifeReaders: 39000,
    reviewCount: 14000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "for-you",
  },
  {
    id: "ready-player",
    title: "Ready Player One",
    author: "Ernest Cline",
    cover: cover("9780307887443"),
    color: "#2a5a8a",
    description:
      "In a bleak 2045, Wade Watts escapes into the OASIS, a vast virtual world. When its creator leaves an Easter egg hunt worth an empire, Wade joins a contest that blurs game and life.",
    genres: ["Sci-Fi", "Adventure"],
    averageRating: 4.2,
    pageCount: 374,
    readLifeReaders: 71000,
    reviewCount: 29000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "mood",
  },
  {
    id: "recursion",
    title: "Recursion",
    author: "Blake Crouch",
    cover: cover("9781524759780"),
    color: "#3a2a5a",
    description:
      "NYPD detective Barry Sutton investigates False Memory Syndrome—people who suddenly remember entire lives they never lived. A mind-bending thriller about time, grief, and the danger of rewriting the past.",
    genres: ["Sci-Fi", "Thriller"],
    averageRating: 4.15,
    pageCount: 329,
    readLifeReaders: 45000,
    reviewCount: 16000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "trending",
  },

  // —— Fantasy ——
  {
    id: "mistborn",
    title: "Mistborn: The Final Empire",
    author: "Brandon Sanderson",
    cover: cover("9780765311788"),
    color: "#4a3a5a",
    description:
      "In a world ruled by the immortal Lord Ruler, street urchin Vin discovers she is a Mistborn—able to burn metals for incredible powers. A crew of thieves plans the ultimate heist: overthrow an empire.",
    genres: ["Fantasy"],
    averageRating: 4.45,
    pageCount: 541,
    readLifeReaders: 78000,
    reviewCount: 32000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "for-you",
  },
  {
    id: "name-wind",
    title: "The Name of the Wind",
    author: "Patrick Rothfuss",
    cover: cover("9780756404741"),
    color: "#6b4a2a",
    description:
      "Kvothe, legendary and ruined, tells the true story of his youth: a troupe of players, a university of magic, a girl named Denna, and the darkness that unmade his life.",
    genres: ["Fantasy"],
    averageRating: 4.5,
    pageCount: 662,
    readLifeReaders: 82000,
    reviewCount: 35000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "for-you",
  },
  {
    id: "gideon-ninth",
    title: "Gideon the Ninth",
    author: "Tamsyn Muir",
    cover: cover("9781250313195"),
    color: "#6a2a3a",
    description:
      "Swordswoman Gideon Nav is forced to serve as cavalier to her childhood nemesis, necromancer Harrowhark, in a deadly contest among the Houses. Lesbian necromancers in space—with bones, banter, and murder.",
    genres: ["Fantasy", "Sci-Fi", "LGBTQ+"],
    averageRating: 4.2,
    pageCount: 448,
    readLifeReaders: 34000,
    reviewCount: 12000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "hidden-gems",
    recommendationReason: "Weird in the best way—fits your darker fantasy streak.",
  },
  {
    id: "poppy-war",
    title: "The Poppy War",
    author: "R.F. Kuang",
    cover: cover("9780062662569"),
    color: "#8a3a2a",
    description:
      "Rin claws her way from orphaned peasant to elite military academy—and awakens a shamanic power tied to gods of war. Inspired by Chinese history, this is a brutal coming-of-age about empire and vengeance.",
    genres: ["Fantasy", "Historical"],
    averageRating: 4.2,
    pageCount: 544,
    readLifeReaders: 48000,
    reviewCount: 17000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "trending",
  },
  {
    id: "cruel-prince",
    title: "The Cruel Prince",
    author: "Holly Black",
    cover: cover("9780316310277"),
    color: "#2a5a4a",
    description:
      "Human Jude Duarte was stolen to Faerie as a child. To survive among cruel princes and court intrigue, she must become more cunning than the immortals who despise her.",
    genres: ["Fantasy", "YA"],
    averageRating: 4.1,
    pageCount: 370,
    readLifeReaders: 69000,
    reviewCount: 27000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "trending",
  },
  {
    id: "acotar",
    title: "A Court of Thorns and Roses",
    author: "Sarah J. Maas",
    cover: cover("9781635575569"),
    color: "#3a5a3a",
    description:
      "Huntress Feyre kills a wolf in the woods—and is dragged to a magical land as punishment. Beauty-and-the-beast romance blooms into a darker war for Prythian’s courts.",
    genres: ["Fantasy", "Romance", "YA"],
    averageRating: 4.2,
    pageCount: 419,
    readLifeReaders: 105000,
    reviewCount: 45000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "trending",
  },
  {
    id: "throne-glass",
    title: "Throne of Glass",
    author: "Sarah J. Maas",
    cover: cover("9781619630345"),
    color: "#4a3a6a",
    description:
      "Assassin Celaena Sardothien is offered freedom if she wins a deadly competition to become the King’s Champion. Court secrets, magic, and rivalry await in a glass castle.",
    genres: ["Fantasy", "YA"],
    averageRating: 4.15,
    pageCount: 406,
    readLifeReaders: 88000,
    reviewCount: 36000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "mood",
  },
  {
    id: "iron-flame",
    title: "Iron Flame",
    author: "Rebecca Yarros",
    cover: cover("9781649374172"),
    color: "#6b2a2a",
    description:
      "Violet Sorrengail survived her first year at Basgiath—barely. Now secrets about the war, the dragons, and Xaden Riorson threaten everything she thought she knew.",
    genres: ["Fantasy", "Romance"],
    averageRating: 4.4,
    pageCount: 623,
    readLifeReaders: 74000,
    reviewCount: 28000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "trending",
  },
  {
    id: "neverwhere",
    title: "Neverwhere",
    author: "Neil Gaiman",
    cover: cover("9780062371058"),
    color: "#2a2a3a",
    description:
      "Ordinary Londoner Richard Mayhew helps a wounded girl named Door—and tumbles into London Below, a shadowy city of monsters, markets, and forgotten people.",
    genres: ["Fantasy", "Urban Fantasy"],
    averageRating: 4.15,
    pageCount: 370,
    readLifeReaders: 42000,
    reviewCount: 15000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "mood",
  },
  {
    id: "american-gods",
    title: "American Gods",
    author: "Neil Gaiman",
    cover: coverId(8494659),
    color: "#3a3a2a",
    description:
      "Shadow Moon gets out of prison and takes a job with the enigmatic Mr. Wednesday—entering a war between old gods brought by immigrants and the new gods of media, tech, and belief.",
    genres: ["Fantasy", "Myth"],
    averageRating: 4.1,
    pageCount: 465,
    readLifeReaders: 51000,
    reviewCount: 18000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "outside",
  },
  {
    id: "priory-orange",
    title: "The Priory of the Orange Tree",
    author: "Samantha Shannon",
    cover: cover("9781635570298"),
    color: "#8a5a2a",
    description:
      "An epic standalone fantasy of queens, dragons, and an ancient enemy rising. Across east and west, women of power fight to stop the end of the world.",
    genres: ["Fantasy", "Epic"],
    averageRating: 4.2,
    pageCount: 848,
    readLifeReaders: 36000,
    reviewCount: 12000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "hidden-gems",
  },

  // —— Literary / Contemporary ——
  {
    id: "midnight-library",
    title: "The Midnight Library",
    author: "Matt Haig",
    cover: cover("9780525559474"),
    color: "#2a3a5a",
    description:
      "Between life and death, Nora Seed finds a library of books that let her try the lives she could have lived. A tender novel about regret, possibility, and choosing to stay.",
    genres: ["Literary", "Contemporary"],
    averageRating: 4.0,
    pageCount: 288,
    readLifeReaders: 93000,
    reviewCount: 40000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "trending",
  },
  {
    id: "where-crawdads",
    title: "Where the Crawdads Sing",
    author: "Delia Owens",
    cover: cover("9780735219090"),
    color: "#4a6a4a",
    description:
      "Kya Clark, the “Marsh Girl,” grows up alone in the coastal wilds of North Carolina. When a popular town boy is found dead, her fragile world collides with suspicion, love, and survival.",
    genres: ["Literary", "Mystery", "Coming of Age"],
    averageRating: 4.35,
    pageCount: 368,
    readLifeReaders: 99000,
    reviewCount: 47000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "trending",
  },
  {
    id: "demon-copperhead",
    title: "Demon Copperhead",
    author: "Barbara Kingsolver",
    cover: cover("9780063251922"),
    color: "#6b5a3a",
    description:
      "A modern retelling of David Copperfield set in Appalachia. Demon’s fierce, funny voice charts foster care, the opioid crisis, and the stubborn will to survive.",
    genres: ["Literary", "Contemporary"],
    averageRating: 4.5,
    pageCount: 560,
    readLifeReaders: 42000,
    reviewCount: 15000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "for-you",
  },
  {
    id: "trust",
    title: "Trust",
    author: "Hernan Diaz",
    cover: cover("9780593420317"),
    color: "#5a4a3a",
    description:
      "Four competing narratives circle a Wall Street fortune and a marriage in early 20th-century New York. A puzzle-box novel about money, power, and who gets to write the story.",
    genres: ["Literary", "Historical"],
    averageRating: 3.9,
    pageCount: 402,
    readLifeReaders: 28000,
    reviewCount: 9000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "hidden-gems",
  },
  {
    id: "vanishing-half",
    title: "The Vanishing Half",
    author: "Brit Bennett",
    cover: cover("9780525536291"),
    color: "#7a5a4a",
    description:
      "Twin sisters Desiree and Stella flee their small Southern town—then choose radically different lives, one passing as white. A multi-generational novel about identity, belonging, and the stories we inherit.",
    genres: ["Literary", "Historical"],
    averageRating: 4.15,
    pageCount: 343,
    readLifeReaders: 56000,
    reviewCount: 20000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "for-you",
  },
  {
    id: "little-fires",
    title: "Little Fires Everywhere",
    author: "Celeste Ng",
    cover: cover("9780735224315"),
    color: "#8a4a3a",
    description:
      "In planned-perfect Shaker Heights, the Richardson family collides with enigmatic artist Mia Warren and her daughter. Secrets, motherhood, and privilege catch fire.",
    genres: ["Literary", "Contemporary"],
    averageRating: 4.1,
    pageCount: 338,
    readLifeReaders: 67000,
    reviewCount: 25000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "mood",
  },
  {
    id: "pachinko",
    title: "Pachinko",
    author: "Min Jin Lee",
    cover: cover("9781455563920"),
    color: "#5a3a2a",
    description:
      "A sweeping saga of a Korean family in Japan across the 20th century—love, shame, ambition, and resilience in the face of history’s cruelty.",
    genres: ["Literary", "Historical"],
    averageRating: 4.3,
    pageCount: 490,
    readLifeReaders: 48000,
    reviewCount: 17000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "for-you",
  },
  {
    id: "daisy-jones",
    title: "Daisy Jones & The Six",
    author: "Taylor Jenkins Reid",
    cover: cover("9781524798628"),
    color: "#c45a3a",
    description:
      "An oral history of a legendary 1970s rock band—and the magnetic, complicated Daisy Jones whose voice could make or break them all.",
    genres: ["Literary", "Historical", "Music"],
    averageRating: 4.2,
    pageCount: 355,
    readLifeReaders: 72000,
    reviewCount: 28000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "trending",
  },
  {
    id: "malibu-rising",
    title: "Malibu Rising",
    author: "Taylor Jenkins Reid",
    cover: cover("9781524798659"),
    color: "#3a7a8a",
    description:
      "One legendary party on the Malibu coast in 1983. Four famous siblings, a famous father, and a night that will change their family forever.",
    genres: ["Literary", "Contemporary"],
    averageRating: 4.05,
    pageCount: 369,
    readLifeReaders: 51000,
    reviewCount: 18000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "mood",
  },
  {
    id: "before-coffee",
    title: "Before the Coffee Gets Cold",
    author: "Toshikazu Kawaguchi",
    cover: cover("9781335430991"),
    color: "#8a6a5a",
    description:
      "In a tiny Tokyo café, you can travel back in time—but only under strict rules, and only until your coffee goes cold. Four visitors seek one more conversation with someone they’ve lost.",
    genres: ["Literary", "Magical Realism"],
    averageRating: 3.75,
    pageCount: 272,
    readLifeReaders: 44000,
    reviewCount: 16000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "outside",
  },
  {
    id: "convenience-store",
    title: "Convenience Store Woman",
    author: "Sayaka Murata",
    cover: coverId(9315164),
    color: "#5a7a6a",
    description:
      "Keiko Furukura has worked in a convenience store for 18 years—the one place she understands the rules. A deadpan, sharp novel about conformity and the strange comfort of being “normal.”",
    genres: ["Literary", "Contemporary"],
    averageRating: 3.8,
    pageCount: 163,
    readLifeReaders: 32000,
    reviewCount: 11000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "hidden-gems",
  },
  {
    id: "handmaids",
    title: "The Handmaid's Tale",
    author: "Margaret Atwood",
    cover: cover("9780385490818"),
    color: "#8a2a2a",
    description:
      "In the theocratic Republic of Gilead, Offred is a Handmaid—valued only for her fertility. A landmark dystopia of surveillance, gender, and resistance.",
    genres: ["Literary", "Dystopia", "Classic"],
    averageRating: 4.1,
    pageCount: 311,
    readLifeReaders: 86000,
    reviewCount: 37000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "outside",
  },
  {
    id: "1984",
    title: "1984",
    author: "George Orwell",
    cover: cover("9780451524935"),
    color: "#2a2a2a",
    description:
      "Winston Smith works at the Ministry of Truth, rewriting history for Big Brother. In a world of perpetual war and Thought Police, even love becomes rebellion.",
    genres: ["Literary", "Dystopia", "Classic"],
    averageRating: 4.2,
    pageCount: 328,
    readLifeReaders: 94000,
    reviewCount: 42000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "mood",
  },
  {
    id: "pride-prejudice",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    cover: cover("9780141439518"),
    color: "#6a5a3a",
    description:
      "Elizabeth Bennet’s wit meets Mr. Darcy’s pride in Austen’s sparkling comedy of manners, misunderstandings, and one of literature’s greatest slow burns.",
    genres: ["Classic", "Romance", "Literary"],
    averageRating: 4.3,
    pageCount: 432,
    readLifeReaders: 88000,
    reviewCount: 39000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "for-you",
  },
  {
    id: "beloved",
    title: "Beloved",
    author: "Toni Morrison",
    cover: cover("9781400033416"),
    color: "#3a2a2a",
    description:
      "Sethe escaped slavery—but the past walks back into her Ohio home as a haunting named Beloved. A masterpiece about memory, motherhood, and the afterlife of trauma.",
    genres: ["Literary", "Historical", "Classic"],
    averageRating: 3.95,
    pageCount: 324,
    readLifeReaders: 41000,
    reviewCount: 15000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "outside",
  },
  {
    id: "lincoln-highway",
    title: "The Lincoln Highway",
    author: "Amor Towles",
    cover: cover("9780735222359"),
    color: "#5a6a7a",
    description:
      "In 1954, Emmett Watson leaves a juvenile work farm for Nebraska—planning a new life with his brother. A wrong turn sends them toward New York and an unforgettable cross-country adventure.",
    genres: ["Literary", "Historical", "Adventure"],
    averageRating: 4.2,
    pageCount: 576,
    readLifeReaders: 38000,
    reviewCount: 13000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "mood",
  },
  {
    id: "ministry-time",
    title: "The Ministry of Time",
    author: "Kaliane Bradley",
    cover: cover("9781668045145"),
    color: "#3a5a6a",
    description:
      "A civil servant is assigned to shepherd a Victorian polar explorer snatched from history by a time-travel ministry. Spy craft, romance, and bureaucracy collide in a witty speculative debut.",
    genres: ["Sci-Fi", "Romance", "Literary"],
    averageRating: 3.85,
    pageCount: 352,
    readLifeReaders: 16000,
    reviewCount: 5200,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "hidden-gems",
  },

  // —— Nonfiction ——
  {
    id: "educated",
    title: "Educated",
    author: "Tara Westover",
    cover: cover("9780399590504"),
    color: "#6b5a4a",
    description:
      "Westover grows up in a survivalist family in Idaho without formal schooling—then fights her way to Cambridge and a PhD. A searing memoir about family, belief, and the cost of knowledge.",
    genres: ["Nonfiction", "Memoir"],
    averageRating: 4.45,
    pageCount: 334,
    readLifeReaders: 97000,
    reviewCount: 45000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "trending",
    recommendationReason: "A ReadLife favorite among memoir readers.",
  },
  {
    id: "atomic-habits",
    title: "Atomic Habits",
    author: "James Clear",
    cover: cover("9780735211292"),
    color: "#3a5a6a",
    description:
      "Tiny changes, remarkable results. Clear’s practical framework for building good habits, breaking bad ones, and designing an environment that makes improvement inevitable.",
    genres: ["Nonfiction", "Self-Help"],
    averageRating: 4.35,
    pageCount: 320,
    readLifeReaders: 110000,
    reviewCount: 52000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "trending",
  },
  {
    id: "sapiens",
    title: "Sapiens",
    author: "Yuval Noah Harari",
    cover: cover("9780062316097"),
    color: "#8a6a3a",
    description:
      "A sweeping history of humankind—from cognitive revolution to empire, capitalism, and the stories we invent to cooperate at scale.",
    genres: ["Nonfiction", "History", "Science"],
    averageRating: 4.2,
    pageCount: 443,
    readLifeReaders: 86000,
    reviewCount: 38000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "for-you",
  },
  {
    id: "thinking-fast",
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    cover: cover("9780374533557"),
    color: "#4a4a5a",
    description:
      "Nobel laureate Kahneman maps System 1 and System 2—the fast intuitions and slow deliberations that shape judgment, bias, and the stories we tell ourselves about choice.",
    genres: ["Nonfiction", "Psychology", "Science"],
    averageRating: 4.15,
    pageCount: 499,
    readLifeReaders: 54000,
    reviewCount: 20000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "outside",
  },
  {
    id: "becoming",
    title: "Becoming",
    author: "Michelle Obama",
    cover: cover("9781524763138"),
    color: "#5a3a2a",
    description:
      "From the South Side of Chicago to the White House, Michelle Obama recounts becoming herself—family, ambition, public life, and the private work of belonging.",
    genres: ["Nonfiction", "Memoir"],
    averageRating: 4.45,
    pageCount: 426,
    readLifeReaders: 78000,
    reviewCount: 34000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "trending",
  },
  {
    id: "born-crime",
    title: "Born a Crime",
    author: "Trevor Noah",
    cover: cover("9780399588174"),
    color: "#2a4a3a",
    description:
      "Noah’s comic, moving memoir of growing up mixed-race in apartheid and post-apartheid South Africa—with a fiercely loving mother at the center of every escape.",
    genres: ["Nonfiction", "Memoir", "Humor"],
    averageRating: 4.5,
    pageCount: 304,
    readLifeReaders: 69000,
    reviewCount: 28000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "for-you",
  },
  {
    id: "into-wild",
    title: "Into the Wild",
    author: "Jon Krakauer",
    cover: cover("9780385486804"),
    color: "#4a6a3a",
    description:
      "Krakauer reconstructs Chris McCandless’s journey into the Alaskan wilderness—and the ideals, wounds, and risks that led a young man to leave everything behind.",
    genres: ["Nonfiction", "Adventure", "Biography"],
    averageRating: 4.0,
    pageCount: 207,
    readLifeReaders: 58000,
    reviewCount: 22000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "mood",
  },
  {
    id: "immortal-life",
    title: "The Immortal Life of Henrietta Lacks",
    author: "Rebecca Skloot",
    cover: cover("9781400052189"),
    color: "#6a3a4a",
    description:
      "Henrietta Lacks’s cells—taken without consent—became one of medicine’s most important tools. Skloot braids science history with the Lacks family’s fight for recognition.",
    genres: ["Nonfiction", "Science", "Biography"],
    averageRating: 4.1,
    pageCount: 381,
    readLifeReaders: 47000,
    reviewCount: 17000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "outside",
  },
  {
    id: "quiet",
    title: "Quiet",
    author: "Susan Cain",
    cover: cover("9780307352156"),
    color: "#5a6a7a",
    description:
      "A manifesto for introverts—and a deep look at how a culture that worships extroversion undervalues quiet power, creativity, and deep thought.",
    genres: ["Nonfiction", "Psychology"],
    averageRating: 4.05,
    pageCount: 352,
    readLifeReaders: 52000,
    reviewCount: 19000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "mood",
  },
  {
    id: "bad-blood",
    title: "Bad Blood",
    author: "John Carreyrou",
    cover: cover("9781524731656"),
    color: "#8a2a2a",
    description:
      "The explosive investigation of Theranos and Elizabeth Holmes—how Silicon Valley hype, secrecy, and ambition built a blood-testing empire on a lie.",
    genres: ["Nonfiction", "Business", "True Crime"],
    averageRating: 4.4,
    pageCount: 339,
    readLifeReaders: 48000,
    reviewCount: 17000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "trending",
  },
  {
    id: "crying-hmart",
    title: "Crying in H Mart",
    author: "Michelle Zauner",
    cover: cover("9780525657743"),
    color: "#7a4a5a",
    description:
      "The Japanese Breakfast musician’s memoir of food, grief, and Korean American identity—learning to cook her mother’s dishes after losing her.",
    genres: ["Nonfiction", "Memoir"],
    averageRating: 4.25,
    pageCount: 239,
    readLifeReaders: 51000,
    reviewCount: 18000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "for-you",
  },
  {
    id: "body-keeps-score",
    title: "The Body Keeps the Score",
    author: "Bessel van der Kolk",
    cover: cover("9780143127741"),
    color: "#3a4a5a",
    description:
      "A landmark exploration of how trauma reshapes body and brain—and the therapies that help people reclaim ownership of their lives.",
    genres: ["Nonfiction", "Psychology", "Science"],
    averageRating: 4.45,
    pageCount: 464,
    readLifeReaders: 72000,
    reviewCount: 30000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "trending",
  },
  {
    id: "mans-search",
    title: "Man's Search for Meaning",
    author: "Viktor E. Frankl",
    cover: cover("9780807014271"),
    color: "#4a4a3a",
    description:
      "Psychiatrist Viktor Frankl recounts survival in Nazi concentration camps and the logotherapy insight that meaning—not pleasure—is the deepest human drive.",
    genres: ["Nonfiction", "Memoir", "Psychology"],
    averageRating: 4.35,
    pageCount: 165,
    readLifeReaders: 64000,
    reviewCount: 26000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "for-you",
  },
  {
    id: "night-wiesel",
    title: "Night",
    author: "Elie Wiesel",
    cover: cover("9780374500016"),
    color: "#2a2a2a",
    description:
      "Wiesel’s spare, devastating account of his adolescence in Auschwitz and Buchenwald—a foundational Holocaust testimony about faith, silence, and memory.",
    genres: ["Nonfiction", "Memoir", "History"],
    averageRating: 4.35,
    pageCount: 120,
    readLifeReaders: 58000,
    reviewCount: 24000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "outside",
  },
  {
    id: "killers-flower",
    title: "Killers of the Flower Moon",
    author: "David Grann",
    cover: cover("9780307742483"),
    color: "#6a4a2a",
    description:
      "In the 1920s, members of the Osage Nation were murdered for their oil wealth. Grann’s true-crime history follows the birth of the FBI and a conspiracy America tried to forget.",
    genres: ["Nonfiction", "True Crime", "History"],
    averageRating: 4.15,
    pageCount: 377,
    readLifeReaders: 55000,
    reviewCount: 20000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "trending",
  },
  {
    id: "the-wager",
    title: "The Wager",
    author: "David Grann",
    cover: cover("9780385534260"),
    color: "#2a4a5a",
    description:
      "A shipwreck, a mutiny, and dueling survival stories from an 18th-century British warship. Grann turns a forgotten scandal into a propulsive tale of empire and truth.",
    genres: ["Nonfiction", "History", "Adventure"],
    averageRating: 4.2,
    pageCount: 329,
    readLifeReaders: 32000,
    reviewCount: 11000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "mood",
  },
  {
    id: "say-nothing",
    title: "Say Nothing",
    author: "Patrick Radden Keefe",
    cover: cover("9780385521314"),
    color: "#3a3a4a",
    description:
      "The disappearance of Jean McConville opens a masterful history of the Troubles in Northern Ireland—IRA violence, informants, and the long shadow of silence.",
    genres: ["Nonfiction", "History", "True Crime"],
    averageRating: 4.45,
    pageCount: 441,
    readLifeReaders: 29000,
    reviewCount: 9500,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "hidden-gems",
  },
  {
    id: "empire-pain",
    title: "Empire of Pain",
    author: "Patrick Radden Keefe",
    cover: cover("9780385545686"),
    color: "#5a2a2a",
    description:
      "The Sackler family, OxyContin, and the making of an opioid catastrophe—a devastating portrait of wealth, marketing, and accountability.",
    genres: ["Nonfiction", "Business", "True Crime"],
    averageRating: 4.5,
    pageCount: 535,
    readLifeReaders: 34000,
    reviewCount: 12000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "for-you",
  },
  {
    id: "between-world",
    title: "Between the World and Me",
    author: "Ta-Nehisi Coates",
    cover: cover("9780812993547"),
    color: "#2a2a3a",
    description:
      "Written as a letter to his son, Coates’s meditation on race, America, and the Black body is urgent, lyrical, and unforgettable.",
    genres: ["Nonfiction", "Essays"],
    averageRating: 4.4,
    pageCount: 152,
    readLifeReaders: 45000,
    reviewCount: 17000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "for-you",
  },
  {
    id: "maybe-talk",
    title: "Maybe You Should Talk to Someone",
    author: "Lori Gottlieb",
    cover: cover("9781328662057"),
    color: "#7a6a5a",
    description:
      "Therapist Lori Gottlieb enters therapy herself after a breakup—and finds a generous, funny, deeply human portrait of what healing actually looks like.",
    genres: ["Nonfiction", "Memoir", "Psychology"],
    averageRating: 4.4,
    pageCount: 415,
    readLifeReaders: 43000,
    reviewCount: 16000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "mood",
  },
  {
    id: "deep-work",
    title: "Deep Work",
    author: "Cal Newport",
    cover: cover("9781455586691"),
    color: "#2a3a5a",
    description:
      "In a distracted world, the ability to focus without interruption is a superpower. Newport argues for cultivating deep work—and shows how to do it.",
    genres: ["Nonfiction", "Self-Help", "Business"],
    averageRating: 4.15,
    pageCount: 296,
    readLifeReaders: 48000,
    reviewCount: 17000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "outside",
  },
  {
    id: "range",
    title: "Range",
    author: "David Epstein",
    cover: cover("9780735214484"),
    color: "#4a6a5a",
    description:
      "Why generalists triumph in a specialized world. Epstein challenges early specialization with stories of athletes, scientists, and creators who flourished by exploring widely.",
    genres: ["Nonfiction", "Psychology", "Science"],
    averageRating: 4.15,
    pageCount: 339,
    readLifeReaders: 27000,
    reviewCount: 9000,
    formats: ["Physical", "Ebook", "Audio"],
    discoveryCategory: "hidden-gems",
  },
];
