import type {
  DiscoverBook,
  DiscoverList,
  DiscoverReader,
  MiniGame,
} from "./types";

const cover = (isbn: string) =>
  `https://covers.openlibrary.org/b/isbn/${isbn}-L.jpg`;

export const DISCOVER_BOOKS: DiscoverBook[] = [
  {
    id: "night-circus",
    title: "The Night Circus",
    author: "Erin Morgenstern",
    cover: cover("9780307744432"),
    color: "#2f4a36",
    description:
      "A wondrous competition between two young magicians unfolds within a mysterious circus that only appears at night.",
    genres: ["Fantasy", "Magical Realism"],
    averageRating: 4.25,
    pageCount: 516,
    readLifeReaders: 48200,
    reviewCount: 12600,
    formats: ["Physical", "Ebook", "Audio"],
    friendRating: 4.6,
    followedReadersCount: 18,
  },
  {
    id: "starless-sea",
    title: "The Starless Sea",
    author: "Erin Morgenstern",
    cover: cover("9780385541213"),
    color: "#3a2f4a",
    description:
      "A graduate student discovers a mysterious book that leads him into an underground world of stories and lost lovers.",
    genres: ["Fantasy", "Magical Realism"],
    averageRating: 4.1,
    pageCount: 512,
    readLifeReaders: 21400,
    reviewCount: 5400,
    formats: ["Physical", "Ebook", "Audio"],
    recommendationReason: "Because you gave The Night Circus 5★.",
    discoveryCategory: "for-you",
    friendRating: 4.3,
    followedReadersCount: 9,
  },
  {
    id: "piranesi",
    title: "Piranesi",
    author: "Susanna Clarke",
    cover: cover("9781635575637"),
    color: "#3d5a6c",
    description:
      "In a labyrinthine House of endless halls and statues, a man named Piranesi records the tides and the dead.",
    genres: ["Fantasy", "Literary"],
    averageRating: 4.4,
    pageCount: 272,
    readLifeReaders: 31800,
    reviewCount: 8900,
    formats: ["Physical", "Ebook", "Audio"],
    recommendationReason: "Based on your Reader DNA.",
    discoveryCategory: "for-you",
    followedReadersCount: 12,
  },
  {
    id: "six-crows",
    title: "Six of Crows",
    author: "Leigh Bardugo",
    cover: cover("9781627792127"),
    color: "#5c3d2e",
    description:
      "A crew of outcasts attempts an impossible heist in the underbelly of Ketterdam.",
    genres: ["Fantasy", "YA"],
    averageRating: 4.5,
    pageCount: 465,
    readLifeReaders: 61200,
    reviewCount: 18200,
    formats: ["Physical", "Ebook", "Audio"],
  },
  {
    id: "achilles",
    title: "The Song of Achilles",
    author: "Madeline Miller",
    cover: cover("9780062060624"),
    color: "#8b5a2b",
    description:
      "A retelling of the Iliad through the eyes of Patroclus, bound to Achilles by love and fate.",
    genres: ["Literary", "Historical", "Romance"],
    averageRating: 4.35,
    pageCount: 416,
    readLifeReaders: 55400,
    reviewCount: 20100,
    formats: ["Physical", "Ebook", "Audio"],
  },
  {
    id: "circe",
    title: "Circe",
    author: "Madeline Miller",
    cover: cover("9780316556347"),
    color: "#5a6b3a",
    description:
      "The witch Circe finds her power on a lonely island, transforming gods, monsters, and herself.",
    genres: ["Fantasy", "Literary", "Myth"],
    averageRating: 4.3,
    pageCount: 393,
    readLifeReaders: 49800,
    reviewCount: 15400,
    formats: ["Physical", "Ebook", "Audio"],
    recommendationReason: "Similar to three of your favorites.",
    discoveryCategory: "for-you",
  },
  {
    id: "mexico",
    title: "Mexican Gothic",
    author: "Silvia Moreno-Garcia",
    cover: cover("9780525620785"),
    color: "#4a3a2a",
    description:
      "A glamorous socialite arrives at a crumbling mansion in 1950s Mexico and finds something rotten beneath the floorboards.",
    genres: ["Horror", "Gothic", "Historical"],
    averageRating: 3.75,
    pageCount: 301,
    readLifeReaders: 18600,
    reviewCount: 6200,
    formats: ["Physical", "Ebook", "Audio"],
    recommendationReason:
      "Because you often finish atmospheric fantasy.",
    discoveryCategory: "for-you",
  },
  {
    id: "ninth-house",
    title: "Ninth House",
    author: "Leigh Bardugo",
    cover: cover("9781250313072"),
    color: "#2a3550",
    description:
      "Galaxy “Alex” Stern monitors Yale’s secret societies—and the ghosts that haunt them.",
    genres: ["Fantasy", "Dark Academia", "Mystery"],
    averageRating: 4.05,
    pageCount: 479,
    readLifeReaders: 27300,
    reviewCount: 7800,
    formats: ["Physical", "Ebook", "Audio"],
    recommendationReason: "Popular among readers you follow.",
    discoveryCategory: "for-you",
  },
  {
    id: "ink-blood",
    title: "Ink Blood Sister Scribe",
    author: "Emma Törzs",
    cover: cover("9780063253452"),
    color: "#5a3a4a",
    description:
      "Two estranged sisters inherit a magical library that keeps them alive—and hunted.",
    genres: ["Fantasy", "Literary"],
    averageRating: 4.15,
    pageCount: 416,
    readLifeReaders: 1200,
    reviewCount: 340,
    formats: ["Physical", "Ebook"],
    recommendationReason: "Readers with similar taste loved this.",
    discoveryCategory: "hidden-gems",
  },
  {
    id: "sea-tranquility",
    title: "Sea of Tranquility",
    author: "Emily St. John Mandel",
    cover: cover("9780593321447"),
    color: "#3a4a5c",
    description:
      "Across centuries, a detective investigates a strange anomaly linking a forest, a moon colony, and a pandemic novel.",
    genres: ["Literary", "Sci-Fi"],
    averageRating: 4.05,
    pageCount: 272,
    readLifeReaders: 980,
    reviewCount: 210,
    formats: ["Physical", "Ebook", "Audio"],
    recommendationReason: "Quietly beloved by Fantasy Wanderers.",
    discoveryCategory: "hidden-gems",
  },
  {
    id: "bunny",
    title: "Bunny",
    author: "Mona Awad",
    cover: cover("9780525559733"),
    color: "#6b3a5a",
    description:
      "A lonely MFA student is drawn into a cultish clique of girls who call each other Bunny—and something darker.",
    genres: ["Literary", "Horror", "Dark Academia"],
    averageRating: 3.7,
    pageCount: 320,
    readLifeReaders: 486,
    reviewCount: 160,
    formats: ["Physical", "Ebook"],
    recommendationReason: "Only 486 ReadLife readers—worth the hunt.",
    discoveryCategory: "hidden-gems",
  },
  {
    id: "hamnet",
    title: "Hamnet",
    author: "Maggie O'Farrell",
    cover: cover("9780525657606"),
    color: "#5c4a3a",
    description:
      "A luminous imagining of the plague year that took Shakespeare’s son—and the woman who held their family together.",
    genres: ["Historical", "Literary"],
    averageRating: 4.2,
    pageCount: 320,
    readLifeReaders: 1420,
    reviewCount: 480,
    formats: ["Physical", "Ebook", "Audio"],
    recommendationReason: "Character-driven, quietly devastating.",
    discoveryCategory: "hidden-gems",
  },
  {
    id: "babel",
    title: "Babel",
    author: "R.F. Kuang",
    cover: cover("9780063021426"),
    color: "#4a2f2a",
    description:
      "At Oxford’s Royal Institute of Translation, language is magic—and empire’s sharpest weapon.",
    genres: ["Fantasy", "Historical", "Dark Academia"],
    averageRating: 4.2,
    pageCount: 560,
    readLifeReaders: 38900,
    reviewCount: 11200,
    formats: ["Physical", "Ebook", "Audio"],
    recommendationReason: "Trending among Fantasy Wanderers.",
    discoveryCategory: "trending",
  },
  {
    id: "yellowface",
    title: "Yellowface",
    author: "R.F. Kuang",
    cover: cover("9780063250833"),
    color: "#c9a15b",
    description:
      "A struggling writer steals her deceased friend’s manuscript—and watches the internet devour them both.",
    genres: ["Literary", "Thriller"],
    averageRating: 3.85,
    pageCount: 336,
    readLifeReaders: 42100,
    reviewCount: 9800,
    formats: ["Physical", "Ebook", "Audio"],
    recommendationReason: "12 readers you follow added this recently.",
    discoveryCategory: "trending",
  },
  {
    id: "fourth-wing",
    title: "Fourth Wing",
    author: "Rebecca Yarros",
    cover: cover("9781649374042"),
    color: "#6b2a2a",
    description:
      "Violet Sorrengail enters a brutal dragon-rider war college where surviving means everything.",
    genres: ["Fantasy", "Romance"],
    averageRating: 4.55,
    pageCount: 517,
    readLifeReaders: 92000,
    reviewCount: 28000,
    formats: ["Physical", "Ebook", "Audio"],
    recommendationReason: "Popular with 80%+ Reading Matches.",
    discoveryCategory: "trending",
  },
  {
    id: "tomorrow",
    title: "Tomorrow, and Tomorrow, and Tomorrow",
    author: "Gabrielle Zevin",
    cover: cover("9780593321201"),
    color: "#6b3a4a",
    description:
      "Two friends build a life—and a legendary game—across decades of creative partnership and heartbreak.",
    genres: ["Literary", "Contemporary"],
    averageRating: 4.15,
    pageCount: 416,
    readLifeReaders: 35600,
    reviewCount: 9100,
    formats: ["Physical", "Ebook", "Audio"],
    recommendationReason: "Trending among Literary Dreamers.",
    discoveryCategory: "trending",
  },
  {
    id: "lessons-chemistry",
    title: "Lessons in Chemistry",
    author: "Bonnie Garmus",
    cover: cover("9780385547345"),
    color: "#3a5a6b",
    description:
      "A brilliant chemist in the 1960s becomes an unlikely cooking-show star—and a quiet revolutionary.",
    genres: ["Historical", "Literary", "Humor"],
    averageRating: 4.3,
    pageCount: 400,
    readLifeReaders: 44800,
    reviewCount: 13200,
    formats: ["Physical", "Ebook", "Audio"],
    recommendationReason:
      "You rarely read historical fiction, but readers who share your love of character-driven stories rated this highly.",
    discoveryCategory: "outside",
  },
  {
    id: "project-hail",
    title: "Project Hail Mary",
    author: "Andy Weir",
    cover: cover("9780593135204"),
    color: "#1f4d6e",
    description:
      "A lone astronaut wakes with amnesia and a mission to save Earth—with help from an unexpected friend.",
    genres: ["Sci-Fi", "Adventure"],
    averageRating: 4.5,
    pageCount: 476,
    readLifeReaders: 51000,
    reviewCount: 14500,
    formats: ["Physical", "Ebook", "Audio"],
    recommendationReason:
      "Outside your usual shelf—readers with your taste finished this in two nights.",
    discoveryCategory: "outside",
  },
  {
    id: "silent-patient",
    title: "The Silent Patient",
    author: "Alex Michaelides",
    cover: cover("9781250301697"),
    color: "#4a2f3a",
    description:
      "A famous painter shoots her husband and never speaks again. A psychotherapist becomes obsessed with why.",
    genres: ["Thriller", "Mystery"],
    averageRating: 4.1,
    pageCount: 336,
    readLifeReaders: 67000,
    reviewCount: 19000,
    formats: ["Physical", "Ebook", "Audio"],
    recommendationReason: "A twisty detour from your fantasy shelf.",
    discoveryCategory: "outside",
  },
  {
    id: "night-film",
    title: "Night Film",
    author: "Marisha Pessl",
    cover: cover("9780812978643"),
    color: "#1a1a2e",
    description:
      "A disgraced journalist investigates the death of a cult filmmaker’s daughter through a labyrinth of secrets.",
    genres: ["Mystery", "Thriller", "Literary"],
    averageRating: 3.8,
    pageCount: 624,
    readLifeReaders: 8200,
    reviewCount: 2100,
    formats: ["Physical", "Ebook"],
  },
  {
    id: "house-sky",
    title: "The House in the Cerulean Sea",
    author: "TJ Klune",
    cover: cover("9781250217288"),
    color: "#3a6b7a",
    description:
      "A by-the-book caseworker is sent to a magical orphanage—and finds a family that rewrites the rules.",
    genres: ["Fantasy", "Cozy", "Found Family"],
    averageRating: 4.4,
    pageCount: 398,
    readLifeReaders: 40200,
    reviewCount: 11800,
    formats: ["Physical", "Ebook", "Audio"],
    recommendationReason: "Cozy & comforting with found family vibes.",
    discoveryCategory: "mood",
  },
  {
    id: "a-little-life",
    title: "A Little Life",
    author: "Hanya Yanagihara",
    cover: cover("9780804172707"),
    color: "#6b5a3a",
    description:
      "Four friends navigate decades of love, ambition, and unbearable pain in New York.",
    genres: ["Literary", "Contemporary"],
    averageRating: 4.3,
    pageCount: 720,
    readLifeReaders: 28900,
    reviewCount: 9500,
    formats: ["Physical", "Ebook", "Audio"],
    recommendationReason: "For when you want to feel everything.",
    discoveryCategory: "mood",
  },
  {
    id: "thursday-murder",
    title: "The Thursday Murder Club",
    author: "Richard Osman",
    cover: cover("9781984880987"),
    color: "#5a6b4a",
    description:
      "Four retirees in a peaceful community solve cold cases—until a real murder lands on their doorstep.",
    genres: ["Mystery", "Humor", "Cozy"],
    averageRating: 4.05,
    pageCount: 368,
    readLifeReaders: 33500,
    reviewCount: 8700,
    formats: ["Physical", "Ebook", "Audio"],
    recommendationReason: "Short & sweet mystery energy.",
    discoveryCategory: "mood",
  },
  {
    id: "normal-people",
    title: "Normal People",
    author: "Sally Rooney",
    cover: cover("9781984822172"),
    color: "#7a5a4a",
    description:
      "Connell and Marianne circle each other through school and university, never quite saying what they mean.",
    genres: ["Literary", "Romance", "Contemporary"],
    averageRating: 3.85,
    pageCount: 273,
    readLifeReaders: 41200,
    reviewCount: 14000,
    formats: ["Physical", "Ebook", "Audio"],
    recommendationReason: "Slow burn, character-first.",
    discoveryCategory: "mood",
  },
  {
    id: "hobbit",
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    cover: cover("9780547928227"),
    color: "#3a5a3a",
    description:
      "Bilbo Baggins is swept into an unexpected adventure with dwarves, a dragon, and a very important ring.",
    genres: ["Fantasy", "Classics", "Adventure"],
    averageRating: 4.3,
    pageCount: 300,
    readLifeReaders: 88000,
    reviewCount: 32000,
    formats: ["Physical", "Ebook", "Audio"],
  },
  {
    id: "acomaf",
    title: "A Court of Mist and Fury",
    author: "Sarah J. Maas",
    cover: cover("9781619635197"),
    color: "#4a2a5a",
    description:
      "Feyre returns to the Spring Court—and discovers a darker, deeper power waiting beyond it.",
    genres: ["Fantasy", "Romance", "YA"],
    averageRating: 4.6,
    pageCount: 624,
    readLifeReaders: 95000,
    reviewCount: 41000,
    formats: ["Physical", "Ebook", "Audio"],
  },
  {
    id: "evelyn-hugo",
    title: "The Seven Husbands of Evelyn Hugo",
    author: "Taylor Jenkins Reid",
    cover: cover("9781501161933"),
    color: "#8a3a5a",
    description:
      "A reclusive Hollywood icon finally tells the truth about her seven marriages—and one impossible love.",
    genres: ["Literary", "Historical", "Romance"],
    averageRating: 4.45,
    pageCount: 400,
    readLifeReaders: 102000,
    reviewCount: 48000,
    formats: ["Physical", "Ebook", "Audio"],
  },
  {
    id: "legends-lattes",
    title: "Legends & Lattes",
    author: "Travis Baldree",
    cover: cover("9781250886088"),
    color: "#6b4a2a",
    description:
      "An orc retires from adventuring to open a coffee shop—and finds a found family instead.",
    genres: ["Fantasy", "Cozy", "Found Family"],
    averageRating: 4.2,
    pageCount: 304,
    readLifeReaders: 36000,
    reviewCount: 9800,
    formats: ["Physical", "Ebook", "Audio"],
  },
  {
    id: "jonathan-strange",
    title: "Jonathan Strange & Mr Norrell",
    author: "Susanna Clarke",
    cover: cover("9780765356154"),
    color: "#2a3a4a",
    description:
      "In an alternate Napoleonic England, two magicians revive English magic—with consequences.",
    genres: ["Fantasy", "Historical", "Literary"],
    averageRating: 3.9,
    pageCount: 1006,
    readLifeReaders: 22000,
    reviewCount: 7100,
    formats: ["Physical", "Ebook", "Audio"],
  },
  {
    id: "iewu",
    title: "It Ends With Us",
    author: "Colleen Hoover",
    cover: cover("9781501110368"),
    color: "#7a4a5c",
    description:
      "A woman torn between the man she loves and the man who once broke her world.",
    genres: ["Romance", "Contemporary"],
    averageRating: 4.2,
    pageCount: 384,
    readLifeReaders: 110000,
    reviewCount: 52000,
    formats: ["Physical", "Ebook", "Audio"],
  },
  {
    id: "atlas",
    title: "The Atlas Six",
    author: "Olivie Blake",
    cover: cover("9781250854513"),
    color: "#2a3550",
    description:
      "Six of the world's most powerful young magicians compete for initiation into a secret society.",
    genres: ["Fantasy", "Dark Academia"],
    averageRating: 3.6,
    pageCount: 384,
    readLifeReaders: 28000,
    reviewCount: 8900,
    formats: ["Physical", "Ebook", "Audio"],
  },
];

export const DISCOVER_READERS: DiscoverReader[] = [
  {
    id: "mina",
    displayName: "Mina",
    username: "minareads",
    avatar: "/avatars/1.png",
    readingPersonality: "The Trusted Recommender",
    favoriteGenres: ["Fantasy", "Literary Fiction", "Romance"],
    currentBook: "Piranesi",
    readingMatch: 87,
    matchReasons: [
      "atmospheric fantasy",
      "character-driven stories",
      "slow-burn books",
    ],
    followers: 2840,
    following: 312,
    section: "similar",
  },
  {
    id: "jordan",
    displayName: "Jordan",
    username: "jordanshelf",
    avatar: "/avatars/2.png",
    readingPersonality: "The Cozy Cartographer",
    favoriteGenres: ["Cozy Fantasy", "Romance", "Mystery"],
    currentBook: "The House in the Cerulean Sea",
    readingMatch: 79,
    matchReasons: ["found family", "gentle fantasy", "rainy-day reads"],
    followers: 1520,
    following: 410,
    section: "similar",
  },
  {
    id: "sam",
    displayName: "Sam",
    username: "samreadsweird",
    avatar: "/avatars/3.png",
    readingPersonality: "The Genre Nomad",
    favoriteGenres: ["Literary", "Horror", "Sci-Fi"],
    currentBook: "Bunny",
    readingMatch: 61,
    matchReasons: ["literary experiments", "emotional intensity"],
    followers: 980,
    following: 220,
    section: "broaden",
  },
  {
    id: "priya",
    displayName: "Priya",
    username: "priyapages",
    avatar: "/avatars/4.png",
    readingPersonality: "The History Whisperer",
    favoriteGenres: ["Historical", "Literary", "Memoir"],
    currentBook: "Hamnet",
    readingMatch: 54,
    matchReasons: ["character depth", "quiet devastation"],
    followers: 2100,
    following: 180,
    section: "broaden",
  },
  {
    id: "leo",
    displayName: "Leo",
    username: "leolists",
    avatar: "/avatars/5.png",
    readingPersonality: "The List Alchemist",
    favoriteGenres: ["Fantasy", "Romance", "YA"],
    currentBook: "Fourth Wing",
    readingMatch: 72,
    matchReasons: ["fantasy favorites", "recommendation taste"],
    followers: 5640,
    following: 190,
    section: "list-makers",
  },
  {
    id: "nova",
    displayName: "Nova",
    username: "novanightreads",
    avatar: "/avatars/6.png",
    readingPersonality: "The Night Owl Curator",
    favoriteGenres: ["Fantasy", "Magical Realism", "Poetry"],
    currentBook: "The Starless Sea",
    readingMatch: 84,
    matchReasons: ["Night Circus adjacent", "dreamlike prose"],
    followers: 3210,
    following: 260,
    section: "list-makers",
  },
  {
    id: "casey",
    displayName: "Casey",
    username: "caseyjuststarted",
    avatar: "/avatars/2.png",
    readingPersonality: "The Fresh Chapter",
    favoriteGenres: ["Fantasy", "Contemporary"],
    currentBook: "Six of Crows",
    readingMatch: 68,
    matchReasons: ["early fantasy favorites"],
    followers: 42,
    following: 88,
    section: "new",
  },
  {
    id: "river",
    displayName: "River",
    username: "riverreads",
    avatar: "/avatars/4.png",
    readingPersonality: "The Soft Critic",
    favoriteGenres: ["Literary", "Romance"],
    currentBook: "Normal People",
    readingMatch: 70,
    matchReasons: ["emotional fiction"],
    followers: 156,
    following: 204,
    section: "new",
  },
  {
    id: "haze",
    displayName: "Haze",
    username: "hazebooks",
    avatar: "/avatars/3.png",
    readingPersonality: "The Mood Matcher",
    favoriteGenres: ["Thriller", "Fantasy", "Horror"],
    currentBook: "Ninth House",
    readingMatch: 76,
    matchReasons: ["dark academia adjacent"],
    followers: 890,
    following: 340,
    section: "friends-follow",
  },
  {
    id: "ellie",
    displayName: "Ellie",
    username: "elliechapter",
    avatar: "/avatars/1.png",
    readingPersonality: "The Comfort Reader",
    favoriteGenres: ["Cozy", "Romance", "Mystery"],
    currentBook: "The Thursday Murder Club",
    readingMatch: 65,
    matchReasons: ["comfort reads"],
    followers: 1200,
    following: 450,
    section: "friends-follow",
  },
];

export const DISCOVER_LISTS: DiscoverList[] = [
  {
    id: "altered-brain",
    title: "Books That Permanently Altered My Brain",
    description:
      "The ones I still think about on random Tuesdays. Proceed with emotional caution.",
    creatorId: "mina",
    tags: ["Literary", "Devastating", "Favorites"],
    bookIds: ["a-little-life", "piranesi", "hamnet", "circe", "night-circus", "achilles"],
    saveCount: 2800,
    readerCount: 742,
    completionCount: 314,
    section: "trending",
  },
  {
    id: "feel-like-dreams",
    title: "Books That Feel Like Dreams",
    description: "Soft edges, strange halls, and stories that refuse to stay on the page.",
    creatorId: "nova",
    tags: ["Magical Realism", "Atmospheric"],
    bookIds: ["starless-sea", "piranesi", "night-circus", "sea-tranquility", "ink-blood"],
    saveCount: 1940,
    readerCount: 512,
    completionCount: 188,
    section: "for-you",
  },
  {
    id: "cozy-fantasy-beginners",
    title: "Beginner's Guide to Cozy Fantasy",
    description: "Low stakes, warm drinks, and found families. Perfect rainy-day shelf.",
    creatorId: "jordan",
    tags: ["Cozy", "Fantasy", "Beginner"],
    bookIds: ["house-sky", "thursday-murder", "circe", "starless-sea"],
    saveCount: 4210,
    readerCount: 1204,
    completionCount: 680,
    section: "trending",
  },
  {
    id: "hate-fantasy",
    title: "Fantasy for People Who Think They Hate Fantasy",
    description: "Gateway books with literary heart and almost no map-required lore.",
    creatorId: "leo",
    tags: ["Fantasy", "Gateway"],
    bookIds: ["piranesi", "house-sky", "circe", "babel", "night-circus"],
    saveCount: 3560,
    readerCount: 980,
    completionCount: 410,
    section: "for-you",
  },
  {
    id: "rainy-sunday",
    title: "Books for a Rainy Sunday",
    description: "One sitting, soft light, and nowhere else to be.",
    creatorId: "ellie",
    tags: ["Short", "Cozy", "Mood"],
    bookIds: ["piranesi", "thursday-murder", "sea-tranquility", "normal-people"],
    saveCount: 1680,
    readerCount: 430,
    completionCount: 290,
    section: "short",
  },
  {
    id: "destroy-you",
    title: "Short Books That Will Destroy You",
    description: "Under 300 pages. Emotionally illegal.",
    creatorId: "sam",
    tags: ["Short", "Devastating"],
    bookIds: ["piranesi", "normal-people", "bunny", "sea-tranquility"],
    saveCount: 5120,
    readerCount: 1800,
    completionCount: 920,
    section: "short",
  },
  {
    id: "found-family",
    title: "Found Family Done Right",
    description: "Chosen families, soft landings, and people who stay.",
    creatorId: "jordan",
    tags: ["Found Family", "Comfort"],
    bookIds: ["house-sky", "six-crows", "tomorrow", "circe"],
    saveCount: 2340,
    readerCount: 670,
    completionCount: 310,
    section: "following",
  },
  {
    id: "first-time-again",
    title: "Books I Wish I Could Read Again for the First Time",
    description: "Irreplaceable first-page magic.",
    creatorId: "mina",
    tags: ["Favorites", "Reread"],
    bookIds: ["night-circus", "six-crows", "piranesi", "project-hail", "babel"],
    saveCount: 6100,
    readerCount: 2100,
    completionCount: 1400,
    section: "following",
  },
  {
    id: "nothing-happens",
    title: "Books Where Nothing Happens but Somehow Everything Happens",
    description: "Quiet novels that rearrange you anyway.",
    creatorId: "priya",
    tags: ["Literary", "Quiet"],
    bookIds: ["normal-people", "hamnet", "sea-tranquility", "tomorrow"],
    saveCount: 890,
    readerCount: 260,
    completionCount: 95,
    section: "outside",
  },
  {
    id: "no-miscomm",
    title: "Romance Without Miscommunication",
    description: "Adults who talk. Miracles do happen.",
    creatorId: "nova",
    tags: ["Romance", "Trope Subversion"],
    bookIds: ["achilles", "normal-people", "house-sky", "tomorrow"],
    saveCount: 1420,
    readerCount: 380,
    completionCount: 140,
    section: "outside",
  },
];

export const MINI_GAMES: MiniGame[] = [
  {
    id: "bookle",
    title: "Bookle",
    description:
      "A Wordle-style word game with literary themes — LOTR, Harry Potter, and more.",
    playable: true,
  },
  {
    id: "bookworm",
    title: "BOOKWORM",
    description:
      "Devour books on the Cozy Shelf — grow, combo, and chase three stars.",
    playable: true,
  },
  {
    id: "guess-the-book",
    title: "Guess the Book",
    description: "Can you recognize a book from increasingly obvious clues?",
    playable: true,
  },
  {
    id: "cover-puzzle",
    title: "Cover Puzzle",
    description: "Piece the cover together before time runs out.",
    playable: false,
  },
  {
    id: "shelf-sort",
    title: "Shelf Sort",
    description: "Put books where they belong before the clock runs out.",
    playable: false,
  },
  {
    id: "book-bingo",
    title: "Book Bingo",
    description: "Generate a reading challenge from your own library.",
    playable: false,
  },
  {
    id: "genre-dash",
    title: "Genre Dash",
    description: "How quickly can you identify a book's genre?",
    playable: false,
  },
  {
    id: "know-your-library",
    title: "How Well Do You Know Your Library?",
    description: "Questions based on books you've actually logged.",
    playable: true,
  },
];

export const MOODS = [
  { id: "cry", label: "Make Me Cry" },
  { id: "cozy", label: "Cozy & Comforting" },
  { id: "cant-stop", label: "Can't Put It Down" },
  { id: "dark", label: "Dark & Twisty" },
  { id: "romantic", label: "Romantic" },
  { id: "transport", label: "Transport Me Somewhere Else" },
  { id: "short", label: "Short & Sweet" },
  { id: "think", label: "Make Me Think" },
  { id: "magical", label: "Magical" },
  { id: "funny", label: "Funny" },
  { id: "slow-burn", label: "Slow Burn" },
  { id: "found-family", label: "Found Family" },
] as const;

export const MOOD_BOOK_MAP: Record<string, string[]> = {
  cry: ["a-little-life", "hamnet", "achilles", "normal-people"],
  cozy: ["house-sky", "thursday-murder", "circe"],
  "cant-stop": ["fourth-wing", "six-crows", "project-hail", "babel"],
  dark: ["ninth-house", "silent-patient", "bunny", "mexico"],
  romantic: ["achilles", "normal-people", "fourth-wing"],
  transport: ["starless-sea", "night-circus", "piranesi", "babel"],
  short: ["piranesi", "sea-tranquility", "normal-people"],
  think: ["babel", "sea-tranquility", "tomorrow", "yellowface"],
  magical: ["night-circus", "starless-sea", "circe", "ink-blood"],
  funny: ["thursday-murder", "lessons-chemistry", "bunny"],
  "slow-burn": ["normal-people", "achilles", "night-circus"],
  "found-family": ["house-sky", "six-crows", "tomorrow"],
};

export function getBookById(id: string) {
  return DISCOVER_BOOKS.find((b) => b.id === id);
}

export function getReaderById(id: string) {
  return DISCOVER_READERS.find((r) => r.id === id);
}

export function getReaderByUsername(username: string) {
  const clean = username.replace(/^@/, "");
  return DISCOVER_READERS.find((r) => r.username === clean);
}

export function getListById(id: string) {
  return DISCOVER_LISTS.find((l) => l.id === id);
}

export function booksByCategory(category: DiscoverBook["discoveryCategory"]) {
  return DISCOVER_BOOKS.filter((b) => b.discoveryCategory === category);
}

export function searchAll(query: string) {
  const q = query.trim().toLowerCase();
  if (!q) {
    return { books: [], readers: [], lists: [], games: [] };
  }
  const books = DISCOVER_BOOKS.filter(
    (b) =>
      b.title.toLowerCase().includes(q) ||
      b.author.toLowerCase().includes(q) ||
      b.genres.some((g) => g.toLowerCase().includes(q)),
  );
  const readers = DISCOVER_READERS.filter(
    (r) =>
      r.displayName.toLowerCase().includes(q) ||
      r.username.toLowerCase().includes(q) ||
      r.readingPersonality.toLowerCase().includes(q),
  );
  const lists = DISCOVER_LISTS.filter(
    (l) =>
      l.title.toLowerCase().includes(q) ||
      l.description.toLowerCase().includes(q) ||
      l.tags.some((t) => t.toLowerCase().includes(q)),
  );
  const games = MINI_GAMES.filter((g) =>
    g.title.toLowerCase().includes(q),
  );
  return { books, readers, lists, games };
}

export function autocompleteSuggestions(query: string) {
  const q = query.trim().toLowerCase();
  if (q.length < 2) return { books: [], authors: [], lists: [] };
  const books = DISCOVER_BOOKS.filter((b) =>
    b.title.toLowerCase().includes(q),
  ).slice(0, 4);
  const authorSet = new Map<string, string>();
  DISCOVER_BOOKS.forEach((b) => {
    if (b.author.toLowerCase().includes(q)) authorSet.set(b.author, b.author);
  });
  const authors = [...authorSet.values()].slice(0, 3);
  const lists = DISCOVER_LISTS.filter((l) =>
    l.title.toLowerCase().includes(q),
  ).slice(0, 3);
  return { books, authors, lists };
}
