/**
 * Official ReadLife Reading Personality System v1.0 — 16 type definitions (verbatim).
 * Best ReadLife Features may include future/conceptual labels shown in result UI only.
 */
import type { PersonalityCode, PersonalityDefinition } from "./types";

export const PERSONALITIES: Record<PersonalityCode, PersonalityDefinition> = {
  EIPS: {
    code: "EIPS",
    emoji: "\ud83e\udded",
    name: "The Story Adventurer",
    motto: "There are too many worlds to stay in one.",
    poles: ["Explorer", "Immersive", "Planner", "Social"],
    summary: "An adventurous, enthusiastic reader who turns curiosity into intentional reading experiences and often brings other people along.",
    longExplanation: "Story Adventurers deliberately make reading exciting.\n\nThey seek unfamiliar worlds, authors, genres and formats, but unlike spontaneous explorers, they enjoy turning curiosity into plans.\n\nA Story Adventurer might create themed reading months, participate in challenges, organize buddy reads and maintain an ambitious TBR.\n\nReading is both personal adventure and shared experience.\n\nThey frequently become the friend who says:\n\n“Okay, we're doing a fantasy month. I already made the list.”",
    strengths: ["Curious", "Enthusiastic", "Adventurous", "Motivating", "Community-oriented", "Goal-driven"],
    watchOuts: ["Creating unrealistic reading plans.", "Turning leisure into another schedule.", "Trying to participate in too many challenges."],
    superpower: "Turning curiosity into actual reading adventures.",
    kryptonite: "Believing twelve books is a reasonable monthly TBR.",
    tbrStyle: "Organized chaos with ambitious categories.",
    socialReadingStyle: "“Come read this with me.”",
    recommendationStyle: "Enthusiastic discovery sharing.",
    suggestedChallenge: "Around the World Reading Passport.",
    suggestedFeatures: ["Discovery Passport", "Reading Parties", "Challenges", "Curated Guides", "Monthly TBR"],
    suggestedRoom: "World-traveler library filled with maps, souvenirs and books from everywhere.",
    suggestedPet: "Red panda with a tiny backpack.",
  },
  EIPO: {
    code: "EIPO",
    emoji: "\ud83d\uddfa\ufe0f",
    name: "The World Wanderer",
    motto: "Give me somewhere I've never been.",
    poles: ["Explorer", "Immersive", "Planner", "Solo"],
    summary: "A deliberate explorer who seeks new reading experiences while treating reading itself as a deeply private journey.",
    longExplanation: "World Wanderers love discovering unfamiliar stories but rarely wander without purpose.\n\nThey may plan a translated-fiction month, work through a new genre or create a personal reading challenge.\n\nUnlike their more social Explorer counterparts, however, the experience is primarily internal.\n\nBooks allow them to quietly travel beyond their ordinary world.",
    strengths: ["Curious", "Independent", "Consistent", "Open-minded", "Introspective"],
    watchOuts: ["Maintaining too many private reading projects.", "Making elaborate reading plans nobody else knows exist."],
    superpower: "Expanding their reading universe intentionally.",
    kryptonite: "Finishing one reading project and immediately designing another.",
    tbrStyle: "Purposeful collections and reading journeys.",
    socialReadingStyle: "Selective but thoughtful.",
    recommendationStyle: "“This opened an entirely new world for me.”",
    suggestedChallenge: "Personal Reading Expedition.",
    suggestedFeatures: ["Discovery Passport", "Museum", "Advanced TBR", "Reading Goals", "Personal Journeys"],
    suggestedRoom: "Observatory library.",
    suggestedPet: "Owl.",
  },
  EAPS: {
    code: "EAPS",
    emoji: "\ud83d\udd0e",
    name: "The Literary Scout",
    motto: "I found something. You need to read this.",
    poles: ["Explorer", "Analytical", "Planner", "Social"],
    summary: "A deliberate discovery-oriented reader who finds interesting books and knows exactly who should read them.",
    longExplanation: "Literary Scouts venture beyond obvious recommendations.\n\nThey seek unusual authors, overlooked books, indie releases and unfamiliar genres—but they also think carefully about what they discover.\n\nThey rarely stop at:\n\n“This was good.”\n\nInstead:\n\n“This was excellent specifically if you enjoy character-driven fantasy with political tension but hate dense exposition.”\n\nThese readers can become some of ReadLife’s most valuable curators.",
    strengths: ["Discovery", "Discernment", "Articulation", "Curiosity", "Community contribution"],
    watchOuts: ["Turning casual recommendations into presentations.", "Becoming slightly offended when nobody listens until the book becomes popular later."],
    superpower: "Finding hidden gems before everyone else.",
    kryptonite: "Watching everyone discover a book six months after you recommended it.",
    tbrStyle: "Carefully curated exploration.",
    socialReadingStyle: "Active recommender.",
    recommendationStyle: "Highly personalized.",
    suggestedChallenge: "Hidden Gem Hunter.",
    suggestedFeatures: ["Curated Guides", "Recommendation Trust", "Indie Spotlight", "Creator Studio", "Discovery"],
    suggestedRoom: "Explorer's study.",
    suggestedPet: "Clever fox.",
  },
  EAPO: {
    code: "EAPO",
    emoji: "\ud83c\udfdb\ufe0f",
    name: "The Curious Scholar",
    motto: "I want to understand what I haven't encountered yet.",
    poles: ["Explorer", "Analytical", "Planner", "Solo"],
    summary: "An independent, intellectually curious reader who deliberately stretches their reading world.",
    longExplanation: "Curious Scholars read with intention and curiosity.\n\nTheir TBR may contain experimental fiction, translated literature, essays, unusual nonfiction, obscure backlist novels and books nobody around them has heard of.\n\nThey enjoy understanding what makes a book distinctive.\n\nReading is both exploration and intellectual discovery.",
    strengths: ["Depth", "Independence", "Curiosity", "Critical thinking", "Intentional exploration"],
    watchOuts: ["Researching what to read for too long.", "Falling into endless literary rabbit holes."],
    superpower: "Deep literary exploration.",
    kryptonite: "The “related works” section.",
    tbrStyle: "Structured and ambitious.",
    socialReadingStyle: "Quiet participant.",
    recommendationStyle: "Precise and considered.",
    suggestedChallenge: "Literary Explorer.",
    suggestedFeatures: ["Reader DNA", "Museum", "Discovery Passport", "Advanced Analytics"],
    suggestedRoom: "Dark academic archive.",
    suggestedPet: "Raven.",
  },
  EIMS: {
    code: "EIMS",
    emoji: "\ud83e\udd8b",
    name: "The Book Butterfly",
    motto: "WAIT. That sounds amazing.",
    poles: ["Explorer", "Immersive", "Mood Reader", "Social"],
    summary: "An enthusiastic, spontaneous reader whose attention is constantly being captured by another exciting story.",
    longExplanation: "Book Butterflies follow excitement wherever it goes.\n\nFriend recommendation?\nAdded.\n\nBeautiful cover?\nAdded.\n\nRandom indie fantasy with fourteen ratings?\nAdded.\n\nBookTok video at 1:43 a.m.?\nUnfortunately added.\n\nThey read emotionally, explore constantly and love telling others about whatever currently has their attention.\n\nTheir reading life may look chaotic from the outside, but curiosity repeatedly leads them toward unexpected favorites.",
    strengths: ["Enthusiasm", "Openness", "Discovery", "Spontaneity", "Social energy"],
    watchOuts: ["The TBR.", "Honestly, just the entire TBR."],
    superpower: "Infectious reading enthusiasm.",
    kryptonite: "Literally any interesting book.",
    tbrStyle: "Structurally unsound.",
    socialReadingStyle: "Highly expressive.",
    recommendationStyle: "Passionate and immediate.",
    suggestedChallenge: "Surprise-Me Challenge.",
    suggestedFeatures: ["Blind Book Match", "TBR Roulette", "Reading Parties", "Discovery", "Social Recommendations"],
    suggestedRoom: "Eclectic colorful reading den.",
    suggestedPet: "Curious ferret.",
  },
  EIMO: {
    code: "EIMO",
    emoji: "\ud83c\udf19",
    name: "The Dream Wanderer",
    motto: "I'll know what I want when I find it.",
    poles: ["Explorer", "Immersive", "Mood Reader", "Solo"],
    summary: "A private, instinctive reader who moves between books according to curiosity and emotion.",
    longExplanation: "Dream Wanderers allow reading instinct to guide them.\n\nThey may spend weeks obsessed with epic fantasy before suddenly deciding they need a quiet memoir.\n\nReading is emotional, atmospheric and deeply personal.\n\nTheir TBR is not really a plan.\n\nIt is a collection of possible futures.",
    strengths: ["Intuition", "Emotional openness", "Flexibility", "Curiosity", "Imagination"],
    watchOuts: ["Difficulty predicting the next read.", "Accidentally ignoring every reading plan."],
    superpower: "Finding unexpected emotional favorites.",
    kryptonite: "Schedules.",
    tbrStyle: "A collection of possibilities rather than obligations.",
    socialReadingStyle: "Quiet but deeply invested.",
    recommendationStyle: "“This made me feel something.”",
    suggestedChallenge: "Follow Your Mood.",
    suggestedFeatures: ["Mood Discovery", "Blind Match", "Reading Room", "Gentle Goals", "Flexible TBR"],
    suggestedRoom: "Moonlit attic library.",
    suggestedPet: "Sleepy cat.",
  },
  EAMS: {
    code: "EAMS",
    emoji: "\ud83d\udce1",
    name: "The Tastemaker",
    motto: "Trust me. This one's going to be big.",
    poles: ["Explorer", "Analytical", "Mood Reader", "Social"],
    summary: "A culturally curious, discerning reader who is constantly finding interesting new voices and sharing them.",
    longExplanation: "Tastemakers like discovering books before everyone else.\n\nThey're open to trends without being controlled by them.\n\nThey enjoy figuring out why a book works, spotting unusual ideas and introducing other readers to new voices.\n\nThey can be especially valuable to indie authors because they are willing to try books without enormous social proof.",
    strengths: ["Discernment", "Curiosity", "Influence", "Cultural awareness", "Discovery"],
    watchOuts: ["Having extremely strong opinions about books nobody has read yet.", "Watching an old recommendation suddenly become “a hidden gem.”"],
    superpower: "Spotting interesting books before the crowd.",
    kryptonite: "People rediscovering something you already told them about.",
    tbrStyle: "Trend-responsive but eclectic.",
    socialReadingStyle: "Highly influential.",
    recommendationStyle: "“You're sleeping on this.”",
    suggestedChallenge: "Indie Discovery Challenge.",
    suggestedFeatures: ["Indie Spotlight", "Guides", "Creator Studio", "Discovery Analytics"],
    suggestedRoom: "Creative loft library.",
    suggestedPet: "Magpie.",
  },
  EAMO: {
    code: "EAMO",
    emoji: "\ud83c\udfb2",
    name: "The Wildcard Critic",
    motto: "I'll read almost anything. Impress me.",
    poles: ["Explorer", "Analytical", "Mood Reader", "Solo"],
    summary: "An unpredictable, curious and independent reader whose broad interests are matched by strong personal judgment.",
    longExplanation: "Wildcard Critics are difficult to predict.\n\nTheir curiosity is broad, but curiosity does not mean low standards.\n\nThey might adore an experimental novella with fifty readers and give the year's biggest bestseller two stars.\n\nPopularity has little effect on their judgment.",
    strengths: ["Independence", "Range", "Discernment", "Curiosity", "Original thinking"],
    watchOuts: ["Recommendation algorithms may struggle with them.", "Being extremely difficult to shop for."],
    superpower: "Forming genuinely independent opinions.",
    kryptonite: "Everyone insisting they MUST love something.",
    tbrStyle: "Random-looking but perfectly logical in the moment.",
    socialReadingStyle: "Observant and selective.",
    recommendationStyle: "Unpredictable but insightful.",
    suggestedChallenge: "Wildcard Roulette.",
    suggestedFeatures: ["Reader DNA", "Experimental Discovery", "Advanced Recommendations", "Blind Match"],
    suggestedRoom: "Eclectic private studio.",
    suggestedPet: "Black cat.",
  },
  LIPS: {
    code: "LIPS",
    emoji: "\u2764\ufe0f",
    name: "The Devoted Enthusiast",
    motto: "If I love it, you're hearing about it.",
    poles: ["Loyalist", "Immersive", "Planner", "Social"],
    summary: "A passionate reader who forms strong attachments to favorite authors, series and fictional worlds—and recruits everyone else.",
    longExplanation: "Devoted Enthusiasts do not casually enjoy books.\n\nThey develop relationships with them.\n\nFavorite author?\nAutomatic preorder.\n\nFavorite series?\nRelease day is an event.\n\nFavorite fictional world?\nEssentially a second residence.\n\nThey love sharing those obsessions with other readers.",
    strengths: ["Loyalty", "Passion", "Community building", "Enthusiasm", "Commitment"],
    watchOuts: ["Waiting years for sequels.", "Becoming emotionally dependent on fictional universes."],
    superpower: "Turning fandom into community.",
    kryptonite: "Series cliffhangers.",
    tbrStyle: "Favorite authors and anticipated releases first.",
    socialReadingStyle: "Extremely communal.",
    recommendationStyle: "Evangelical.",
    suggestedChallenge: "Series Completion Quest.",
    suggestedFeatures: ["Author Rooms", "Launch Events", "Buddy Reads", "Fandom Spaces"],
    suggestedRoom: "Fandom sanctuary.",
    suggestedPet: "Golden retriever.",
  },
  LIPO: {
    code: "LIPO",
    emoji: "\u2615",
    name: "The Comfort Collector",
    motto: "I know what feels like home.",
    poles: ["Loyalist", "Immersive", "Planner", "Solo"],
    summary: "A deeply personal reader who builds a carefully curated library around stories that feel meaningful and familiar.",
    longExplanation: "Comfort Collectors value depth over novelty.\n\nTheir favorite books become places they return to.\n\nThey may buy several editions of the same beloved novel.\n\nTheir shelves are not just records of what they read.\n\nThey are emotional archives.",
    strengths: ["Emotional depth", "Loyalty", "Intentionality", "Self-awareness", "Attachment"],
    watchOuts: ["Special editions.", "Buying a fourth copy of the same book."],
    superpower: "Building a deeply personal reading life.",
    kryptonite: "Beautiful editions of books they already own.",
    tbrStyle: "Carefully selected.",
    socialReadingStyle: "Intimate and selective.",
    recommendationStyle: "Personal and heartfelt.",
    suggestedChallenge: "Comfort Classics.",
    suggestedFeatures: ["Reading Museum", "Favorites Hall", "Quote Wall", "Reading Memories"],
    suggestedRoom: "Warm cottage library.",
    suggestedPet: "Sleeping tabby.",
  },
  LAPS: {
    code: "LAPS",
    emoji: "\ud83d\udcdd",
    name: "The Book Club Scholar",
    motto: "Okay, but what did everyone think about Chapter 17?",
    poles: ["Loyalist", "Analytical", "Planner", "Social"],
    summary: "A structured, thoughtful reader who loves understanding books through discussion.",
    longExplanation: "Book Club Scholars remember details.\n\nThey have questions.\n\nThey probably have tabs.\n\nThey definitely have opinions.\n\nThey enjoy both reading and analyzing what they read with other people.\n\nTheir ideal book club is one where everyone actually read the book.",
    strengths: ["Discussion", "Interpretation", "Consistency", "Thoughtfulness", "Organization"],
    watchOuts: ["Unprepared book-club members.", "Someone saying “it was boring” and refusing to elaborate."],
    superpower: "Elevating book discussions.",
    kryptonite: "“I didn't finish, but here's my opinion.”",
    tbrStyle: "Structured around clubs and goals.",
    socialReadingStyle: "Discussion-oriented.",
    recommendationStyle: "Evidence included.",
    suggestedChallenge: "Discussion Leader.",
    suggestedFeatures: ["Book Clubs", "Chapter Discussions", "Curated Guides", "Reading Parties"],
    suggestedRoom: "Library discussion salon.",
    suggestedPet: "Spectacled owl.",
  },
  LAPO: {
    code: "LAPO",
    emoji: "\ud83e\udd43",
    name: "The Quiet Connoisseur",
    motto: "I don't need to read everything. I want to read well.",
    poles: ["Loyalist", "Analytical", "Planner", "Solo"],
    summary: "A selective, intentional reader with a strong understanding of personal taste.",
    longExplanation: "Quiet Connoisseurs know themselves.\n\nThey do not need every trending release.\n\nTheir TBR may be smaller than other people's, but every title earned its place.\n\nThey research carefully, choose intentionally and read without needing outside validation.",
    strengths: ["Selectivity", "Discipline", "Judgment", "Independence", "Self-knowledge"],
    watchOuts: ["Expectations can become extremely high.", "The carefully researched disappointment hurts more."],
    superpower: "Knowing exactly what works for them.",
    kryptonite: "A book failing after weeks of anticipation.",
    tbrStyle: "Curated and highly prioritized.",
    socialReadingStyle: "Reserved.",
    recommendationStyle: "Selective and precise.",
    suggestedChallenge: "Curator's Shelf.",
    suggestedFeatures: ["Advanced TBR", "Personal Analytics", "Collections", "Museum"],
    suggestedRoom: "Refined private library.",
    suggestedPet: "Tortoise.",
  },
  LIMS: {
    code: "LIMS",
    emoji: "\ud83d\udd25",
    name: "The Passion Chaser",
    motto: "I'm not over it. Don't ask when I'll be over it.",
    poles: ["Loyalist", "Immersive", "Mood Reader", "Social"],
    summary: "A deeply emotional reader who knows their favorite kinds of stories and becomes intensely invested when one hits correctly.",
    longExplanation: "Passion Chasers know exactly which kinds of stories emotionally destroy them.\n\nAnd they continue choosing those stories willingly.\n\nWhen they become obsessed, everybody knows.\n\nQuotes are sent.\n\nFriends are recruited.\n\nCharacter edits are watched.\n\nRecovery is unlikely.",
    strengths: ["Passion", "Emotional depth", "Connection", "Enthusiasm", "Loyalty"],
    watchOuts: ["Severe book hangovers.", "Becoming unbearable while waiting for friends to reach THAT chapter."],
    superpower: "Loving stories wholeheartedly.",
    kryptonite: "“Are you at that part yet?”",
    tbrStyle: "Familiar favorites selected according to mood.",
    socialReadingStyle: "Expressive fandom.",
    recommendationStyle: "“PLEASE READ THIS.”",
    suggestedChallenge: "Emotional Damage Bingo.",
    suggestedFeatures: ["Buddy Reads", "Quote Wall", "Fandom Spaces", "Reading Parties"],
    suggestedRoom: "Candlelit quote-covered den.",
    suggestedPet: "Tiny dragon.",
  },
  LIMO: {
    code: "LIMO",
    emoji: "\ud83e\uddf8",
    name: "The Cozy Drifter",
    motto: "I'm reading whatever feels right.",
    poles: ["Loyalist", "Immersive", "Mood Reader", "Solo"],
    summary: "A private, comfort-oriented reader who chooses familiar reading territory according to emotional need.",
    longExplanation: "Cozy Drifters know the kinds of stories that usually work for them.\n\nBut they do not want reading to become another task.\n\nTheir mood decides what part of their familiar reading world they visit today.\n\nSometimes the best book is not the most ambitious book.\n\nIt is simply the book they need.",
    strengths: ["Intuition", "Comfort", "Self-awareness", "Emotional connection", "Flexibility"],
    watchOuts: ["Remaining permanently inside the comfort zone.", "Ignoring every book people insist they “have to” read."],
    superpower: "Choosing the right book for the right moment.",
    kryptonite: "“You HAVE to read this.”",
    tbrStyle: "Mood-based.",
    socialReadingStyle: "Private and low-pressure.",
    recommendationStyle: "Comfort-oriented.",
    suggestedChallenge: "Cozy Quest.",
    suggestedFeatures: ["Cozy Reading Mode", "Mood Discovery", "Gentle Streaks", "Reading Room"],
    suggestedRoom: "Rainy cottage nook.",
    suggestedPet: "Fluffy rabbit.",
  },
  LAMS: {
    code: "LAMS",
    emoji: "\ud83d\udcda",
    name: "The Trusted Recommender",
    motto: "Tell me what you like. I'll find you a book.",
    poles: ["Loyalist", "Analytical", "Mood Reader", "Social"],
    summary: "A discerning social reader who knows both their own taste and everyone else's remarkably well.",
    longExplanation: "Trusted Recommenders know their territory.\n\nMore importantly, they remember everyone else's.\n\nThey know:\n- Which friend hates third-act breakups.\n- Which one needs fast pacing.\n- Which one loves tragic endings.\n- Which one will absolutely forgive terrible plot logic if the romance works.\n\nThey are human recommendation engines.",
    strengths: ["Recommendation skill", "Memory", "Discernment", "Social awareness", "Taste expertise"],
    watchOuts: ["Recommending something for two years and watching someone discover it from TikTok.", "Becoming the unpaid librarian of the friend group."],
    superpower: "Matching readers with books.",
    kryptonite: "“Have you heard of this book?” Yes. They told you about it.",
    tbrStyle: "Flexible but taste-focused.",
    socialReadingStyle: "Highly useful community member.",
    recommendationStyle: "Personalized.",
    suggestedChallenge: "Recommendation Matchmaker.",
    suggestedFeatures: ["Curated Guides", "Recommendation Trust", "Creator Analytics", "Friend Matching"],
    suggestedRoom: "Librarian's recommendation desk.",
    suggestedPet: "Border collie.",
  },
  LAMO: {
    code: "LAMO",
    emoji: "\ud83d\udc08\u200d\u2b1b",
    name: "The Selective Critic",
    motto: "I know what I like. Impress me.",
    poles: ["Loyalist", "Analytical", "Mood Reader", "Solo"],
    summary: "An independent reader who may choose books spontaneously but has extremely clear standards.",
    longExplanation: "Selective Critics know what works for them.\n\nPopularity carries little weight.\n\nConsensus carries little weight.\n\nTheir own reaction matters.\n\nThey may decide spontaneously what to read, but their taste itself is anything but random.",
    strengths: ["Self-knowledge", "Independence", "Discernment", "Strong judgment", "Resistance to hype"],
    watchOuts: ["Becoming so selective that nothing sounds good.", "Endless browsing followed by rereading something trusted."],
    superpower: "Being resistant to hype.",
    kryptonite: "“But everyone on TikTok gave it five stars.”",
    tbrStyle: "Highly specific mood options.",
    socialReadingStyle: "Selective observer.",
    recommendationStyle: "Honest and exacting.",
    suggestedChallenge: "Beat the Algorithm.",
    suggestedFeatures: ["Advanced Recommendations", "Reader DNA", "Personal Analytics", "Recommendation Controls"],
    suggestedRoom: "Moody minimalist study.",
    suggestedPet: "Judgmental black cat.",
  }
};

export function getPersonality(code: PersonalityCode): PersonalityDefinition {
  return PERSONALITIES[code];
}

/** Format type code with middle dots: EAMS → E·A·M·S */
export function formatPersonalityCode(code: string): string {
  return code.split("").join("·");
}

export function personalityDisplayName(code: PersonalityCode): string {
  const p = PERSONALITIES[code];
  return `${p.emoji} ${p.name}`;
}
