import type { ForumPost, CommunityReview } from "./types";
import { getBookById } from "@/components/search/data";

type BookSocial = {
  forum: Omit<ForumPost, "id">[];
  reviews: Omit<CommunityReview, "id">[];
};

function pack(bookId: string, data: BookSocial): {
  forum: ForumPost[];
  reviews: CommunityReview[];
} {
  return {
    forum: data.forum.map((p, i) => ({ ...p, id: `${bookId}-f${i + 1}` })),
    reviews: data.reviews.map((r, i) => ({ ...r, id: `${bookId}-r${i + 1}` })),
  };
}

function fallbackSocial(bookId: string): {
  forum: ForumPost[];
  reviews: CommunityReview[];
} {
  const book = getBookById(bookId);
  const title = book?.title ?? "this one";
  const author = book?.author ?? "the author";
  const genre = book?.genres[0] ?? "read";
  const isNf = book?.genres.some((g) => g === "Nonfiction") ?? false;
  const seed = bookId.split("").reduce((a, c) => a + c.charCodeAt(0), 0);

  const forumBodies = isNf
    ? [
        `Halfway through ${title} and the framing already feels sharper than most ${genre.toLowerCase()} I’ve read this year.`,
        `Anyone else annotating heavily? ${author} keeps landing lines I want to argue with and underline.`,
        `Finished last night. Still turning over the ending—curious what stuck with you most.`,
      ]
    : [
        `Just started ${title}. The opening pages already have that ${genre.toLowerCase()} pull—anyone else diving in?`,
        `Midway check-in on ${title}: characters are doing the work. No spoilers, but the middle shift hit hard.`,
        `Closing thoughts on ${title} (light spoilers in replies please). ${author} stuck the landing for me.`,
      ];

  const reviewBodies = isNf
    ? [
        `${title} is the rare ${genre.toLowerCase()} that stays with you after you close it. Clear voice, real stakes, and ideas you keep applying.`,
        `Not every chapter lands equally, but when ${author} is sharp, it’s unforgettable. Glad it’s on ReadLife.`,
      ]
    : [
        `${title} delivers exactly what I wanted from ${genre.toLowerCase()}—strong voice, memorable set pieces, and characters I still think about.`,
        `A few pacing dips aside, ${author} made this one of my favorite recent reads in the genre.`,
      ];

  return {
    forum: [
      {
        id: `${bookId}-f1`,
        username: ["inkbound", "pagesandrain", "shelfwalker", "nightreader"][
          seed % 4
        ],
        title: isNf ? `Notes from ${title}` : `Thoughts on ${title}`,
        body: forumBodies[0],
        spoilers: false,
        progressPct: 12 + (seed % 20),
        score: 8 + (seed % 20),
        commentCount: 2 + (seed % 8),
      },
      {
        id: `${bookId}-f2`,
        username: ["bookishorbit", "marginnotes", "chapterhop"][seed % 3],
        title: isNf ? `What surprised you?` : `Halfway through ${title}`,
        body: forumBodies[1],
        spoilers: false,
        progressPct: 45 + (seed % 20),
        score: 12 + (seed % 15),
        commentCount: 3 + (seed % 10),
      },
      {
        id: `${bookId}-f3`,
        username: ["aftertheend", "lastpageclub", "rereadready"][seed % 3],
        title: isNf ? `Finished — still thinking` : `Ending discussion`,
        body: forumBodies[2],
        spoilers: !isNf,
        progressPct: 100,
        score: 18 + (seed % 25),
        commentCount: 5 + (seed % 12),
      },
    ],
    reviews: [
      {
        id: `${bookId}-r1`,
        username: ["litlane", "covercrush", "quietstacks"][seed % 3],
        dateLabel: "Aug 4, 2026",
        rating: 3.5 + ((seed % 4) * 0.5),
        body: reviewBodies[0],
        spoilers: false,
        likes: 10 + (seed % 30),
        commentCount: seed % 4,
      },
      {
        id: `${bookId}-r2`,
        username: ["genrehopper", "alwaysannotating"][seed % 2],
        dateLabel: "Jul 22, 2026",
        rating: 3 + ((seed % 5) * 0.5),
        body: reviewBodies[1],
        spoilers: false,
        likes: 4 + (seed % 18),
        commentCount: seed % 3,
      },
    ],
  };
}

/** Book-specific forum + review copy informed by real Goodreads / book-club discourse.
 * Wording is original paraphrase of common reader reactions (not verbatim scrapes).
 */
const RAW: Record<string, BookSocial> = {
  "night-circus": {
    forum: [
      {
        username: "etherealpages",
        title: "The ice garden tent…",
        body: "I’m only a few tents in and already the atmosphere is doing all the work. Less “plot racing” and more wandering Le Cirque des Rêves like a dream you don’t want to wake from.",
        spoilers: false,
        progressPct: 8,
        score: 22,
        commentCount: 6,
      },
      {
        username: "plotfirstreader",
        edited: true,
        title: "Is anyone else waiting for the duel to feel sharper?",
        body: "The circus descriptions are gorgeous, but Celia and Marco’s contest still feels soft to me mid-book. Loving the mood; craving clearer stakes.",
        spoilers: false,
        progressPct: 45,
        score: 11,
        commentCount: 14,
      },
      {
        username: "baileyforever",
        title: "That ending / epilogue",
        body: "The business-card beat wrecked me in the best way. Atmosphere > conventional climax, and I’m fine with that.",
        spoilers: true,
        progressPct: 100,
        score: 41,
        commentCount: 19,
      },
    ],
    reviews: [
      {
        username: "literarywanders",
        dateLabel: "Jul 2, 2026",
        rating: 4.5,
        body: "Lyrical, black-and-white magic. The plot is simple (two magicians, a game, a circus), but the sensory writing makes it feel like literature dressed as fantasy. Flat side characters, unforgettable venue.",
        spoilers: false,
        likes: 28,
        commentCount: 3,
      },
      {
        username: "needsmoreplot",
        dateLabel: "Jun 18, 2026",
        rating: 3,
        body: "Beautiful circus, thin character arcs. I wanted more from the duel and less postcard prose—still glad I visited.",
        spoilers: false,
        likes: 9,
        commentCount: 5,
      },
      {
        username: "minareads",
        dateLabel: "May 9, 2026",
        rating: 5,
        body: "One of my all-time comfort rereads. Unexpected pleasures, star-crossed magic, and that circus that only opens at night.",
        spoilers: false,
        likes: 56,
        commentCount: 2,
        following: true,
      },
    ],
  },
  "starless-sea": {
    forum: [
      {
        username: "doorhunter",
        title: "Found the bee / key / sword",
        body: "Zachary just found the book in the stacks and I’m already vibrating. Anyone else get Night Circus nostalgia but weirder and more nested?",
        spoilers: false,
        progressPct: 5,
        score: 18,
        commentCount: 7,
      },
      {
        username: "storyhoarder",
        title: "How many stories-within-stories is too many?",
        body: "Loving the underground library aesthetic. Halfway through and the nested tales are either genius or dizzying depending on the chapter.",
        spoilers: false,
        progressPct: 52,
        score: 15,
        commentCount: 11,
      },
      {
        username: "mirabelstan",
        title: "Fate of the Harbor",
        body: "The war over the Starless Sea’s archive hit harder than I expected. Pink hair forever.",
        spoilers: true,
        progressPct: 100,
        score: 33,
        commentCount: 8,
      },
    ],
    reviews: [
      {
        username: "bookishbee",
        dateLabel: "Aug 1, 2026",
        rating: 4,
        body: "A love letter to stories and secret doors. Messier than The Night Circus, richer in myth-building. Bring patience for digressions.",
        spoilers: false,
        likes: 21,
        commentCount: 1,
      },
      {
        username: "linearorbye",
        dateLabel: "Jul 14, 2026",
        rating: 2.5,
        body: "Atmosphere for days, plot for minutes. If you need a clean through-line, this labyrinth may frustrate you.",
        spoilers: false,
        likes: 12,
        commentCount: 4,
      },
    ],
  },
  piranesi: {
    forum: [
      {
        username: "hallwalker",
        title: "The Beauty of the House…",
        body: "“…is immeasurable; its Kindness infinite.” I’m cataloguing statues with him and I never want to leave the House.",
        spoilers: false,
        progressPct: 12,
        score: 47,
        commentCount: 9,
      },
      {
        username: "theotherfan",
        title: "Tuesdays and Fridays with the Other",
        body: "Something about those meetings feels… off. Keeping notes. Ontological mystery brain fully activated.",
        spoilers: false,
        progressPct: 40,
        score: 29,
        commentCount: 16,
      },
      {
        username: "tidekeeper",
        title: "When the truth floods in",
        body: "I will not spoil, but if you’re past the halfway point: trust the journals. The House was never what I thought.",
        spoilers: true,
        progressPct: 85,
        score: 38,
        commentCount: 22,
      },
    ],
    reviews: [
      {
        username: "puzzlebox",
        dateLabel: "Aug 8, 2026",
        rating: 5,
        body: "A slim miracle. Infinite halls, tides, statues, and a mystery that unfolds like fog lifting. Women’s Prize energy for a reason.",
        spoilers: false,
        likes: 64,
        commentCount: 4,
      },
      {
        username: "wantedspeed",
        dateLabel: "Jun 22, 2026",
        rating: 3.5,
        body: "Hypnotic first half, slightly colder once the outside world intrudes. Still unique—nothing else feels like this House.",
        spoilers: false,
        likes: 17,
        commentCount: 2,
      },
    ],
  },
  "six-crows": {
    forum: [
      {
        username: "brekkercode",
        title: "Kaz’s gloves lore already?",
        body: "Ketterdam is filthy and I love it. Kaz Brekker introduction alone sold me. Heist crew assemble!!",
        spoilers: false,
        progressPct: 6,
        score: 31,
        commentCount: 8,
      },
      {
        username: "wraithwatch",
        title: "Ice Court prep anxiety",
        body: "The plan is insane. Nina/Matthias tension is eating me alive and we haven’t even breached yet.",
        spoilers: false,
        progressPct: 55,
        score: 44,
        commentCount: 21,
      },
      {
        username: "nojesper",
        title: "THAT cliffhanger",
        body: "You cannot leave a duology like that. I screamed. Crooked Kingdom is downloading as we speak.",
        spoilers: true,
        progressPct: 100,
        score: 72,
        commentCount: 35,
      },
    ],
    reviews: [
      {
        username: "heistgoblin",
        dateLabel: "Aug 4, 2026",
        rating: 5,
        body: "Ocean’s Eleven in a fantasy underworld. Twist machine, found-family crew, zero dull pages. Kaz/Inej and Nina/Matthias both slap.",
        spoilers: false,
        likes: 88,
        commentCount: 6,
      },
      {
        username: "slowmidclaim",
        dateLabel: "May 30, 2026",
        rating: 4,
        body: "People say the middle drags—I disagree. The setup is bait; the Ice Court is the hook. Ending is criminal (complimentary).",
        spoilers: false,
        likes: 34,
        commentCount: 3,
      },
    ],
  },
  achilles: {
    forum: [
      {
        username: "patroclusfirst",
        title: "Phthia days",
        body: "Awkward exile prince meets golden Achilles and I’m already emotionally compromised. Miller’s voice is so intimate.",
        spoilers: false,
        progressPct: 10,
        score: 26,
        commentCount: 5,
      },
      {
        username: "chironstudent",
        title: "Before Troy",
        body: "The training years with Chiron are soft and doomed and I keep rereading the same pages. War is coming and I hate it.",
        spoilers: false,
        progressPct: 48,
        score: 19,
        commentCount: 8,
      },
      {
        username: "iliadcrier",
        title: "I was not okay",
        body: "Famous tearjerker for a reason. If you know the myth you still aren’t prepared. Bring tissues; skip nothing.",
        spoilers: true,
        progressPct: 100,
        score: 91,
        commentCount: 40,
      },
    ],
    reviews: [
      {
        username: "mythgremlin",
        dateLabel: "Jul 28, 2026",
        rating: 5,
        body: "Queer Iliad retelling that makes glory and love collide until something breaks. Orange Prize winner energy: intimate, inevitable, devastating.",
        spoilers: false,
        likes: 77,
        commentCount: 5,
      },
      {
        username: "homernerd",
        dateLabel: "Apr 12, 2026",
        rating: 4,
        body: "Not a beat-for-beat Iliad—and that’s the point. Patroclus’s gaze makes Achilles human. The ending still hurts on reread.",
        spoilers: true,
        likes: 29,
        commentCount: 2,
      },
    ],
  },
  circe: {
    forum: [
      {
        username: "aiaiaexile",
        title: "Not powerful like Helios…",
        body: "Watching Circe discover pharmakeia after being dismissed by the gods is so satisfying. Exile arc loading.",
        spoilers: false,
        progressPct: 15,
        score: 24,
        commentCount: 4,
      },
      {
        username: "odysseusalert",
        title: "Mortals on the island",
        body: "The sailors chapters made my skin crawl—then the pigs. Circe’s agency is the whole point and Miller doesn’t flinch.",
        spoilers: true,
        progressPct: 60,
        score: 37,
        commentCount: 18,
      },
      {
        username: "telegonusfan",
        title: "Motherhood hit different",
        body: "Gods vs mortals choice at the end had me sobbing on the train. Feminist myth reclaim done right.",
        spoilers: true,
        progressPct: 100,
        score: 52,
        commentCount: 11,
      },
    ],
    reviews: [
      {
        username: "classicsmajor",
        dateLabel: "Aug 6, 2026",
        rating: 4.5,
        body: "Epic scale with quiet power. Circe’s isolation, witchcraft, and refusal to stay a side character in someone else’s odyssey. Lush without being empty.",
        spoilers: false,
        likes: 45,
        commentCount: 3,
      },
      {
        username: "melodramacheck",
        dateLabel: "Mar 3, 2026",
        rating: 3.5,
        body: "Gorgeous set pieces and deep Classics knowledge; sometimes the emotional register felt overwrought for me. Still memorable.",
        spoilers: false,
        likes: 14,
        commentCount: 2,
      },
    ],
  },
  mexico: {
    forum: [
      {
        username: "highplaceguest",
        title: "Arrived at High Place",
        body: "Noemí’s lipstick vs this rotting English mansion is the contrast of the century. Mold, silence, bad dinners—gothic unlocked.",
        spoilers: false,
        progressPct: 12,
        score: 27,
        commentCount: 6,
      },
      {
        username: "slowburnhorror",
        title: "Does this pick up?",
        body: "Page ~200 club checking in. Atmosphere is thick; plot is… simmering. Friends say wait for the last stretch.",
        spoilers: false,
        progressPct: 55,
        score: 19,
        commentCount: 23,
      },
      {
        username: "mycologytrauma",
        title: "Okay the ending went THERE",
        body: "Not ghosts. Something worse and weirder. Colonial rot made literal. I’m shook and slightly nauseous.",
        spoilers: true,
        progressPct: 100,
        score: 48,
        commentCount: 31,
      },
    ],
    reviews: [
      {
        username: "gothicgirl",
        dateLabel: "Oct 2, 2025",
        rating: 4,
        body: "Lovecraft-meets-Brontë in 1950s Mexico. Slow first two-thirds, then the horror turns bodily and bizarre. Noemí carries it.",
        spoilers: false,
        likes: 39,
        commentCount: 7,
      },
      {
        username: "wantedjumpscares",
        dateLabel: "Sep 11, 2025",
        rating: 2.5,
        body: "Loved the setup; the climax felt jammed into the last 50 pages and too out-there for me. Writing still stylish.",
        spoilers: false,
        likes: 22,
        commentCount: 9,
      },
    ],
  },
  "ninth-house": {
    forum: [
      {
        username: "lethehouse",
        title: "Alex at Yale already feels cursed",
        body: "Multiple homicide survivor offered a full ride to monitor secret societies… Bardugo adult debut is darker than Grisha and I’m here for it.",
        spoilers: false,
        progressPct: 8,
        score: 33,
        commentCount: 10,
      },
      {
        username: "tombtourist",
        title: "Magic system confusion (affectionate)",
        body: "Halfway: the societies’ rites are vivid and gross. Sometimes I need a chart for who’s binding what. Still compulsively readable.",
        spoilers: false,
        progressPct: 50,
        score: 21,
        commentCount: 14,
      },
      {
        username: "darlingtonwho",
        title: "New Haven is not okay",
        body: "Power, privilege, ghosts, and predation. The ending left me starving for Hell Bent. Dark academia with teeth.",
        spoilers: true,
        progressPct: 100,
        score: 58,
        commentCount: 27,
      },
    ],
    reviews: [
      {
        username: "occultcampus",
        dateLabel: "Aug 10, 2026",
        rating: 4.5,
        body: "Stephen King wasn’t wrong—shocking, twisty, and about real people under elite rot. Slow open, then impossible to put down.",
        spoilers: false,
        likes: 61,
        commentCount: 4,
      },
      {
        username: "grisha4life",
        dateLabel: "Jan 19, 2026",
        rating: 4,
        body: "Different beast from Six of Crows: colder, crueler, more occult procedural. Alex Stern is a fantastic messy heroine.",
        spoilers: false,
        likes: 27,
        commentCount: 1,
      },
    ],
  },
  "ink-blood": {
    forum: [
      {
        username: "scribekeeper",
        title: "Magical books that cost blood",
        body: "Esther in Antarctica vs Joanna in Vermont protecting the library—already obsessed with the sister split.",
        spoilers: false,
        progressPct: 10,
        score: 16,
        commentCount: 3,
      },
      {
        username: "mirrorweird",
        title: "Dad’s death + unknown book",
        body: "The family legacy is so much bigger than their Vermont wards. Feels like Ninth House cousin energy with more bookbinding.",
        spoilers: false,
        progressPct: 55,
        score: 14,
        commentCount: 5,
      },
      {
        username: "halfsisterarc",
        title: "Loyalty vs power",
        body: "The secret spanning continents landed. Wanted a tad more about the other libraries, but the sister reunion paid off.",
        spoilers: true,
        progressPct: 100,
        score: 20,
        commentCount: 4,
      },
    ],
    reviews: [
      {
        username: "spellboundreads",
        dateLabel: "Jul 7, 2026",
        rating: 4,
        body: "Atmospheric debut about dangerous books, estranged sisters, and the price of magic. Quietly suspenseful more than flashy.",
        spoilers: false,
        likes: 18,
        commentCount: 1,
      },
      {
        username: "wantedmoreaction",
        dateLabel: "May 2, 2026",
        rating: 3.5,
        body: "Loved the premise and sibling tension; the middle wanders. Still a hidden gem if you like literary fantasy.",
        spoilers: false,
        likes: 7,
        commentCount: 0,
      },
    ],
  },
  "sea-tranquility": {
    forum: [
      {
        username: "anomalywatch",
        title: "1912 forest glitch",
        body: "That Vancouver Island note already feels like a time scar. Mandel doing quiet apocalypse again.",
        spoilers: false,
        progressPct: 15,
        score: 17,
        commentCount: 4,
      },
      {
        username: "mooncolonist",
        title: "Book tour during a pandemic…",
        body: "Meta in the best way. The threads across centuries are starting to rhyme and I feel gently undone.",
        spoilers: false,
        progressPct: 60,
        score: 22,
        commentCount: 6,
      },
      {
        username: "gasperyfan",
        title: "What endures",
        body: "Time travel as tenderness. Not a thriller—more a meditation. The last movement made me cry on a park bench.",
        spoilers: true,
        progressPct: 100,
        score: 35,
        commentCount: 9,
      },
    ],
    reviews: [
      {
        username: "quietscifi",
        dateLabel: "Jun 30, 2026",
        rating: 4.5,
        body: "Slim, elegiac, interconnected. Pandemic, moon colony, anomaly—Mandel makes vastness feel intimate.",
        spoilers: false,
        likes: 31,
        commentCount: 2,
      },
      {
        username: "wantedplotengine",
        dateLabel: "Feb 14, 2026",
        rating: 3,
        body: "Beautiful sentences; less propulsive than Station Eleven for me. Still thoughtful and worth an afternoon.",
        spoilers: false,
        likes: 8,
        commentCount: 1,
      },
    ],
  },
  bunny: {
    forum: [
      {
        username: "mfasurvivor",
        title: "We call each other Bunny",
        body: "Samantha on scholarship watching the rich workshop girls is already social-horror gold. This is going to get deranged.",
        spoilers: false,
        progressPct: 10,
        score: 25,
        commentCount: 7,
      },
      {
        username: "workshopwitch",
        title: "The parties…",
        body: "Cultish MFA satire crossed with something supernatural and sticky. I laughed, then felt sick, then laughed again.",
        spoilers: true,
        progressPct: 70,
        score: 30,
        commentCount: 12,
      },
      {
        username: "darlingcreature",
        title: "What did I just read",
        body: "Unhinged in a literary way. If you liked dark academia but wanted it meaner and weirder—hello.",
        spoilers: true,
        progressPct: 100,
        score: 28,
        commentCount: 8,
      },
    ],
    reviews: [
      {
        username: "surrealistreader",
        dateLabel: "Aug 2, 2026",
        rating: 4,
        body: "Lonely MFA student + Bunny cult + grotesque transformation energy. Polarizing on purpose. I was delighted and disturbed.",
        spoilers: false,
        likes: 24,
        commentCount: 3,
      },
      {
        username: "tooweirdforme",
        dateLabel: "Dec 1, 2025",
        rating: 2,
        body: "Style over sense by the end. The satire of workshop culture worked; the rest lost me.",
        spoilers: false,
        likes: 11,
        commentCount: 2,
      },
    ],
  },
  hamnet: {
    forum: [
      {
        username: "agnesfirst",
        title: "Not ‘Shakespeare’s wife’—Agnes",
        body: "O’Farrell centering the woman and the child instead of the Famous Man is already healing something in me.",
        spoilers: false,
        progressPct: 12,
        score: 29,
        commentCount: 5,
      },
      {
        username: "plagueyear",
        title: "1596",
        body: "The domestic details are so precise I can smell the herbs. Grief is arriving and I’m not ready.",
        spoilers: false,
        progressPct: 55,
        score: 21,
        commentCount: 7,
      },
      {
        username: "hamletbridge",
        title: "How art holds a child",
        body: "The connection to the play wrecked me without being cheap. A luminous, devastating plague-year novel.",
        spoilers: true,
        progressPct: 100,
        score: 44,
        commentCount: 10,
      },
    ],
    reviews: [
      {
        username: "histficheart",
        dateLabel: "Jul 19, 2026",
        rating: 5,
        body: "Grief made tactile. Agnes is unforgettable; the writing is intimate and fierce. One of the best historical novels of the last decade.",
        spoilers: false,
        likes: 53,
        commentCount: 2,
      },
      {
        username: "wantedmorewill",
        dateLabel: "Jan 8, 2026",
        rating: 4,
        body: "Some readers want more William on the page—I think the restraint is the point. The absence echoes.",
        spoilers: false,
        likes: 16,
        commentCount: 1,
      },
    ],
  },
  babel: {
    forum: [
      {
        username: "silverbars",
        title: "Translation as empire fuel",
        body: "Robin at Babel already feels like paradise with rot under the floorboards. Dark academia with a colonial engine.",
        spoilers: false,
        progressPct: 12,
        score: 36,
        commentCount: 9,
      },
      {
        username: "hermessociety",
        title: "Cohort feelings",
        body: "Ramy / Victoire / Letty dynamics are so lived-in. The moral dilemma of benefiting from the tower while being harmed by it hits hard.",
        spoilers: false,
        progressPct: 50,
        score: 41,
        commentCount: 17,
      },
      {
        username: "footnotefighter",
        title: "Anger earned",
        body: "Some call it didactic—I call it refusing to look away. The siege / ending choices will live in my head rent-free.",
        spoilers: true,
        progressPct: 100,
        score: 55,
        commentCount: 28,
      },
    ],
    reviews: [
      {
        username: "oxfordhaunt",
        dateLabel: "Aug 9, 2026",
        rating: 4.5,
        body: "Language, silver-working, and the violence elegant institutions require. Nebula-winning dark academia that actually argues something.",
        spoilers: false,
        likes: 70,
        commentCount: 8,
      },
      {
        username: "theoryfatigue",
        dateLabel: "Nov 20, 2025",
        rating: 3,
        body: "Ideas are sharp; pacing and characterization uneven for me. Still an important, furious book.",
        spoilers: false,
        likes: 25,
        commentCount: 6,
      },
    ],
  },
  yellowface: {
    forum: [
      {
        username: "junewatcher",
        title: "Athena’s manuscript…",
        body: "June’s impulse decision made me gasp out loud on the bus. Publishing satire with knives out.",
        spoilers: false,
        progressPct: 8,
        score: 32,
        commentCount: 11,
      },
      {
        username: "twitterpileon",
        title: "Juniper Song era",
        body: "The internet swarm chapters are uncomfortably accurate. Unreliable narrator doing cartwheels.",
        spoilers: false,
        progressPct: 55,
        score: 28,
        commentCount: 15,
      },
      {
        username: "whoownsastory",
        title: "How far will she go",
        body: "Addictive and mean. Some readers find June relatable; I find her a horror protagonist in litfic clothing.",
        spoilers: true,
        progressPct: 100,
        score: 39,
        commentCount: 20,
      },
    ],
    reviews: [
      {
        username: "indiesatire",
        dateLabel: "Jul 25, 2026",
        rating: 4,
        body: "Literary theft, identity cosplay, and the publishing machine. Sharp, propulsive, polarizing on purpose.",
        spoilers: false,
        likes: 48,
        commentCount: 5,
      },
      {
        username: "wanteddeeper",
        dateLabel: "Feb 2, 2026",
        rating: 3,
        body: "Page-turner; themes sometimes felt like a checklist. Still a conversation starter.",
        spoilers: false,
        likes: 19,
        commentCount: 3,
      },
    ],
  },
  "fourth-wing": {
    forum: [
      {
        username: "basgiathbound",
        title: "Conscription day dread",
        body: "Violet entering the riders’ quadrant with a chronic illness and a famous mother… forced proximity unlocked. Dragons or die.",
        spoilers: false,
        progressPct: 5,
        score: 40,
        commentCount: 12,
      },
      {
        username: "xadenproblems",
        title: "Enemies to lovers is EARNED",
        body: "Family blood feud + war college + telepathic dragon bonds. The hostility isn’t fake-dating lite. I’m unwell.",
        spoilers: false,
        progressPct: 45,
        score: 63,
        commentCount: 29,
      },
      {
        username: "secondyearplease",
        title: "Ending scream",
        body: "Romantasy doing numbers for a reason. Cliffhanger cruelty. Iron Flame is not optional.",
        spoilers: true,
        progressPct: 100,
        score: 80,
        commentCount: 44,
      },
    ],
    reviews: [
      {
        username: "romantasyqueen",
        dateLabel: "Aug 11, 2026",
        rating: 5,
        body: "Enemies to lovers, dragons, deadly academy. Banter bites, stakes soar. Not subtle—and I did not ask it to be.",
        spoilers: false,
        likes: 102,
        commentCount: 7,
      },
      {
        username: "prosepolice",
        dateLabel: "Jun 3, 2026",
        rating: 3,
        body: "Fun ride; writing and world rules wobbly. If you want polished SFF, look elsewhere. If you want dopamine, climb.",
        spoilers: false,
        likes: 36,
        commentCount: 11,
      },
    ],
  },
  tomorrow: {
    forum: [
      {
        username: "samandsadie",
        title: "Hospital game room meet-cute",
        body: "Childhood connection → lifelong creative partnership. Already bracing for the communication issues everyone warned about.",
        spoilers: false,
        progressPct: 10,
        score: 23,
        commentCount: 6,
      },
      {
        username: "ichigostan",
        title: "Making games / breaking each other",
        body: "The collaboration highs are electric; the interpersonal spiral is frustrating in a very human way. Marx my beloved.",
        spoilers: false,
        progressPct: 60,
        score: 31,
        commentCount: 14,
      },
      {
        username: "perfectworlds",
        title: "Imperfect universe, still making",
        body: "About games and disability and ambition and why we keep loving people anyway. Ending left me quiet for an hour.",
        spoilers: true,
        progressPct: 100,
        score: 47,
        commentCount: 16,
      },
    ],
    reviews: [
      {
        username: "literarygamer",
        dateLabel: "Jul 31, 2026",
        rating: 4.5,
        body: "A romance of the mind across decades of game-making. Tender, volatile, occasionally maddening—like real creative friendship.",
        spoilers: false,
        likes: 58,
        commentCount: 4,
      },
      {
        username: "wantedhealthier",
        dateLabel: "Sep 9, 2025",
        rating: 3.5,
        body: "Loved the games and Marx; struggled with Sam/Sadie’s conflict loop. Still a standout contemporary novel.",
        spoilers: false,
        likes: 20,
        commentCount: 3,
      },
    ],
  },
  "lessons-chemistry": {
    forum: [
      {
        username: "elizabethzott",
        title: "Chemistry ≠ cooking… until it is",
        body: "1960s lab sexism is infuriating on purpose. Elizabeth on a daytime cooking show might be my new religion.",
        spoilers: false,
        progressPct: 20,
        score: 34,
        commentCount: 8,
      },
      {
        username: "sixthirty",
        title: "Mad is teaching America science",
        body: "Supper-time revolution via molecules. Funny, pointed, and weirdly wholesome without being soft.",
        spoilers: false,
        progressPct: 65,
        score: 27,
        commentCount: 5,
      },
      {
        username: "calvinfan",
        title: "Found family in lab coats",
        body: "Harriet, Six-Thirty, the rowing, the grief—cried more than expected from a “comedy.”",
        spoilers: true,
        progressPct: 100,
        score: 42,
        commentCount: 9,
      },
    ],
    reviews: [
      {
        username: "feministfiction",
        dateLabel: "Jun 15, 2026",
        rating: 4.5,
        body: "Brilliant chemist becomes unlikely TV star and quietly rewires the culture. Sharp humor with real stakes.",
        spoilers: false,
        likes: 49,
        commentCount: 2,
      },
      {
        username: "anachronismcheck",
        dateLabel: "Apr 4, 2026",
        rating: 3.5,
        body: "Delightful voice; some 1960s details felt modern-projected. Still a joy to read.",
        spoilers: false,
        likes: 13,
        commentCount: 1,
      },
    ],
  },
  "project-hail": {
    forum: [
      {
        username: "amnesiastronaut",
        title: "Woke up on a spaceship??",
        body: "Ryland Grace with two problems: no memory, extinction-level mission. Weir science-problem energy activated.",
        spoilers: false,
        progressPct: 5,
        score: 38,
        commentCount: 7,
      },
      {
        username: "rockytones",
        title: "First contact but make it friendship",
        body: "Not invasion—partnership. Rocky is the best alien buddy in years. Music as language had me grinning.",
        spoilers: true,
        progressPct: 55,
        score: 71,
        commentCount: 24,
      },
      {
        username: "tauceti",
        title: "Science AND feelings",
        body: "Hard SF that still breaks your heart. Twist-adjacent reveals without cheap mind-screw. Instant reread.",
        spoilers: true,
        progressPct: 100,
        score: 66,
        commentCount: 18,
      },
    ],
    reviews: [
      {
        username: "hardscififan",
        dateLabel: "Aug 7, 2026",
        rating: 5,
        body: "The Martian’s problem-solving DNA plus genuine first-contact friendship. Funny, meticulous, unexpectedly moving.",
        spoilers: false,
        likes: 95,
        commentCount: 6,
      },
      {
        username: "mathskippedme",
        dateLabel: "May 21, 2026",
        rating: 4,
        body: "Some equations skimmed past my brain; Rocky carried me. Best “unlikely friendship in space” I’ve read.",
        spoilers: false,
        likes: 28,
        commentCount: 2,
      },
    ],
  },
  "silent-patient": {
    forum: [
      {
        username: "aliciagallery",
        title: "She never speaks again",
        body: "Painter shoots husband, then silence. Theo the therapist is already circling like a moth. Thriller brain on.",
        spoilers: false,
        progressPct: 8,
        score: 29,
        commentCount: 8,
      },
      {
        username: "groveunit",
        title: "Unreliable everything",
        body: "Halfway and I’m trusting no one. Diary entries + therapy sessions = delicious paranoia.",
        spoilers: false,
        progressPct: 50,
        score: 33,
        commentCount: 13,
      },
      {
        username: "twistvictim",
        title: "The last act",
        body: "Famous twist for a reason. Some guess early; I did not. Propulsive even if the psychology is pulpy.",
        spoilers: true,
        progressPct: 100,
        score: 51,
        commentCount: 26,
      },
    ],
    reviews: [
      {
        username: "thrillerstack",
        dateLabel: "Jul 12, 2026",
        rating: 4,
        body: "Obsession, silence, and a therapist who needs this case too much. Twist-driven; best read cold.",
        spoilers: false,
        likes: 44,
        commentCount: 3,
      },
      {
        username: "litficpurist",
        dateLabel: "Mar 18, 2026",
        rating: 2.5,
        body: "Hooks hard, character depth thinner than the marketing. Fine airplane thriller.",
        spoilers: false,
        likes: 18,
        commentCount: 4,
      },
    ],
  },
  "night-film": {
    forum: [
      {
        username: "cordovacult",
        title: "Stanislas Cordova’s world",
        body: "Disgraced journalist + dead daughter of a cult filmmaker. The scrapbook / multimedia vibe is deliciously eerie.",
        spoilers: false,
        progressPct: 10,
        score: 18,
        commentCount: 4,
      },
      {
        username: "labyrinthine",
        title: "600 pages of rabbit holes",
        body: "Conspiracy tunnels forever. Sometimes brilliant, sometimes exhausting—like falling into a Cordova forum at 3am.",
        spoilers: false,
        progressPct: 60,
        score: 15,
        commentCount: 9,
      },
      {
        username: "ashleymystery",
        title: "Was the truth worth it?",
        body: "Atmosphere wins. Resolution is divisive among my book club—half loved the ambiguity, half wanted cleaner answers.",
        spoilers: true,
        progressPct: 100,
        score: 22,
        commentCount: 11,
      },
    ],
    reviews: [
      {
        username: "darkfilmfan",
        dateLabel: "May 5, 2026",
        rating: 4,
        body: "A maximalist literary thriller about fandom, mythmaking, and a filmmaker who might be a monster. Immersive if you surrender.",
        spoilers: false,
        likes: 19,
        commentCount: 2,
      },
      {
        username: "toolong",
        dateLabel: "Oct 10, 2025",
        rating: 2.5,
        body: "Stylish rabbit hole that overstays. Great premise; needed a tighter edit.",
        spoilers: false,
        likes: 10,
        commentCount: 1,
      },
    ],
  },
  "house-sky": {
    forum: [
      {
        username: "linusbaker",
        title: "Extremely Upper Management called…",
        body: "Caseworker sent to evaluate six “dangerous” magical kids including the Antichrist. Found family sirens already wailing.",
        spoilers: false,
        progressPct: 8,
        score: 45,
        commentCount: 9,
      },
      {
        username: "lucythegnome",
        title: "Marsyas Island soft hours",
        body: "Arthur’s kindness is illegal. Chauncey rights. This book is a hug with bureaucracy jokes.",
        spoilers: false,
        progressPct: 50,
        score: 52,
        commentCount: 14,
      },
      {
        username: "rulesarewrong",
        title: "Chosen family forever",
        body: "Some call it didactic; I needed the message. Finished smiling and slightly wrecked.",
        spoilers: true,
        progressPct: 100,
        score: 61,
        commentCount: 12,
      },
    ],
    reviews: [
      {
        username: "cozyfantasy",
        dateLabel: "Aug 5, 2026",
        rating: 5,
        body: "Heart-on-sleeve found family fantasy. Quirky kids, quiet queer tenderness, and a caseworker learning to choose love over rules.",
        spoilers: false,
        likes: 84,
        commentCount: 5,
      },
      {
        username: "toosweet",
        dateLabel: "Dec 12, 2025",
        rating: 3,
        body: "Charming but saccharine for me. Still appreciate the anti-fear message about “monstrous” children.",
        spoilers: false,
        likes: 15,
        commentCount: 2,
      },
    ],
  },
  "a-little-life": {
    forum: [
      {
        username: "judeobserver",
        title: "Four friends in New York",
        body: "Willem, JB, Malcolm, Jude—ambition and devotion. Already sensing the trauma gravity around Jude.",
        spoilers: false,
        progressPct: 10,
        score: 20,
        commentCount: 8,
      },
      {
        username: "cwheavy",
        title: "Content warnings are not optional",
        body: "Midway check-in: this is friendship as hymn and horror. Take breaks. The writing is relentless and precise.",
        spoilers: false,
        progressPct: 45,
        score: 35,
        commentCount: 22,
      },
      {
        username: "bookerfinalist",
        title: "I finished and I need a week",
        body: "Masterful, punishing, unforgettable. Not for every season of life. Found family and unbearable pain intertwined.",
        spoilers: true,
        progressPct: 100,
        score: 48,
        commentCount: 30,
      },
    ],
    reviews: [
      {
        username: "literaryendurance",
        dateLabel: "Jun 1, 2026",
        rating: 5,
        body: "A portrait of friendship and trauma across decades. Beautiful and brutal. Know your limits before you start.",
        spoilers: false,
        likes: 67,
        commentCount: 9,
      },
      {
        username: "miserypass",
        dateLabel: "Aug 20, 2025",
        rating: 2,
        body: "Exquisitely written suffering that felt exploitative to me. DNFed emotionally even when I finished the pages.",
        spoilers: false,
        likes: 31,
        commentCount: 14,
      },
    ],
  },
  "thursday-murder": {
    forum: [
      {
        username: "elizabethbest",
        title: "Cold cases for fun",
        body: "Four retirees solving murders from a peaceful village—cozy mystery comfort food. Joyce’s diary voice is already iconic.",
        spoilers: false,
        progressPct: 10,
        score: 28,
        commentCount: 5,
      },
      {
        username: "ibrahimnotes",
        title: "First live murder lands",
        body: "When the game becomes real, the club shines. Funny without being frivolous; mysteries with heart.",
        spoilers: false,
        progressPct: 55,
        score: 24,
        commentCount: 6,
      },
      {
        username: "rontheron",
        title: "Whodunit satisfaction",
        body: "Twists landed clean for me. Instant series addiction—someone pass the next Osman.",
        spoilers: true,
        progressPct: 100,
        score: 33,
        commentCount: 7,
      },
    ],
    reviews: [
      {
        username: "cozymysteryfan",
        dateLabel: "Jul 3, 2026",
        rating: 4,
        body: "Charming amateur sleuths, dry humor, and a plot that respects your time. Perfect palate cleanser.",
        spoilers: false,
        likes: 37,
        commentCount: 1,
      },
      {
        username: "hardboiledonly",
        dateLabel: "Jan 22, 2026",
        rating: 3,
        body: "Pleasant but predictable. If you want grit, look elsewhere; if you want tea and clues, dive in.",
        spoilers: false,
        likes: 9,
        commentCount: 0,
      },
    ],
  },
  "normal-people": {
    forum: [
      {
        username: "mariannewatcher",
        title: "Small town magnetism",
        body: "Connell popular / Marianne loner—then that first conversation. Rooney’s understatement is doing violence already.",
        spoilers: false,
        progressPct: 8,
        score: 26,
        commentCount: 7,
      },
      {
        username: "trinityyears",
        title: "Dublin orbit",
        body: "They keep choosing wrong people and circling back. Class, miscommunication, and fixation. I’m yelling at both of them.",
        spoilers: false,
        progressPct: 55,
        score: 30,
        commentCount: 19,
      },
      {
        username: "willthey",
        title: "Why can’t they just talk",
        body: "Finished furious and fond. Some find them self-involved; I found them painfully recognizable.",
        spoilers: true,
        progressPct: 100,
        score: 41,
        commentCount: 23,
      },
    ],
    reviews: [
      {
        username: "millenniallit",
        dateLabel: "May 28, 2026",
        rating: 4,
        body: "Mutual fascination across school and university. Spare prose, huge feelings. The Hulu glow is real but the book is sharper.",
        spoilers: false,
        likes: 52,
        commentCount: 4,
      },
      {
        username: "toxicpass",
        dateLabel: "Nov 3, 2025",
        rating: 2,
        body: "Drama without enough why. Trauma handled thinly for me. Stylish alienation isn’t always depth.",
        spoilers: false,
        likes: 23,
        commentCount: 8,
      },
    ],
  },
  hobbit: {
    forum: [
      {
        username: "bagendhomebody",
        title: "Unexpected party!!",
        body: "Gandalf and dwarves crashed breakfast and Bilbo’s whole life. Reluctant hero origin is cozy chaos.",
        spoilers: false,
        progressPct: 5,
        score: 20,
        commentCount: 3,
      },
      {
        username: "riddlesindark",
        title: "Gollum chapter forever",
        body: "That riddle game still slaps. The ring feels small here and enormous in hindsight. Classic for a reason.",
        spoilers: true,
        progressPct: 45,
        score: 34,
        commentCount: 8,
      },
      {
        username: "smaugeye",
        title: "There and back again",
        body: "Dragon, treasure, and a hobbit who discovers courage. Comfort questing at its finest.",
        spoilers: false,
        progressPct: 100,
        score: 29,
        commentCount: 4,
      },
    ],
    reviews: [
      {
        username: "tolkienuncle",
        dateLabel: "Jun 8, 2026",
        rating: 5,
        body: "The gateway fantasy. Humor, adventure, and moral clarity without being simplistic. Bilbo remains perfect.",
        spoilers: false,
        likes: 40,
        commentCount: 1,
      },
      {
        username: "modernpacing",
        dateLabel: "Feb 2, 2026",
        rating: 3.5,
        body: "Charming; songs and pauses may test impatient readers. Still essential worldbuilding DNA.",
        spoilers: false,
        likes: 7,
        commentCount: 0,
      },
    ],
  },
  acomaf: {
    forum: [
      {
        username: "feyrespring",
        title: "Back from Under the Mountain",
        body: "Trauma hangover is real. Spring Court feels wrong in my bones. Night Court whispering already.",
        spoilers: false,
        progressPct: 10,
        score: 38,
        commentCount: 11,
      },
      {
        username: "batboysupporter",
        title: "Inner Circle unlocked",
        body: "Slow burn + court intrigue + healing. Rhysand discourse will never die and I accept my fate.",
        spoilers: false,
        progressPct: 50,
        score: 55,
        commentCount: 32,
      },
      {
        username: "matingbond",
        title: "Fated mates feelings",
        body: "This is the book that converted me. Ending politics set up the rest of the series beautifully.",
        spoilers: true,
        progressPct: 100,
        score: 70,
        commentCount: 25,
      },
    ],
    reviews: [
      {
        username: "acotarstan",
        dateLabel: "Aug 3, 2026",
        rating: 5,
        body: "Many say this is where the series peaks: character growth, romance payoff, High Lord politics. Spicy and strategic.",
        spoilers: false,
        likes: 91,
        commentCount: 6,
      },
      {
        username: "tamlindefender",
        dateLabel: "Jan 15, 2026",
        rating: 3,
        body: "Loved Feyre’s agency; some love-interest framing felt uneven. Still a compulsive romantasy read.",
        spoilers: false,
        likes: 24,
        commentCount: 10,
      },
    ],
  },
  "evelyn-hugo": {
    forum: [
      {
        username: "moniquegrant",
        title: "Why her?",
        body: "Aging Hollywood icon picks an unknown reporter to tell the truth. Seven husbands is the least interesting part already.",
        spoilers: false,
        progressPct: 8,
        score: 31,
        commentCount: 6,
      },
      {
        username: "oldhollywood",
        title: "Ambition and closets",
        body: "Glamour as armor. The forbidden love thread is the heartbeat—Hollywood survival as queer history.",
        spoilers: false,
        progressPct: 55,
        score: 44,
        commentCount: 15,
      },
      {
        username: "sevenhusbands",
        title: "The real love story",
        body: "I gasped, I sobbed, I called my friend immediately. Confession narrative done right.",
        spoilers: true,
        progressPct: 100,
        score: 68,
        commentCount: 22,
      },
    ],
    reviews: [
      {
        username: "tjrfan",
        dateLabel: "Jul 22, 2026",
        rating: 5,
        body: "Unapologetic Evelyn, devastating love, and the cost of fame. Addictive dual timeline with a purpose.",
        spoilers: false,
        likes: 76,
        commentCount: 3,
      },
      {
        username: "sawitcoming",
        dateLabel: "Sep 30, 2025",
        rating: 3.5,
        body: "Twists telegraphed for me, but Evelyn’s voice still charms. A crowd-pleaser that earns its tears.",
        spoilers: false,
        likes: 14,
        commentCount: 1,
      },
    ],
  },
  "legends-lattes": {
    forum: [
      {
        username: "vivtheorc",
        title: "Hung up the sword for coffee",
        body: "Battle-weary orc opens Thune’s first coffee shop. Cozy fantasy thesis statement in one sentence.",
        spoilers: false,
        progressPct: 5,
        score: 36,
        commentCount: 5,
      },
      {
        username: "cinnamonroll",
        title: "Found family bakeoff",
        body: "Succubus barista, rat friend, local politics—low stakes, high heart. This is a cinnamon roll in book form.",
        spoilers: false,
        progressPct: 50,
        score: 29,
        commentCount: 4,
      },
      {
        username: "softadventure",
        title: "Building something soft",
        body: "No chosen one, just community. Perfect after grimdark burnout.",
        spoilers: false,
        progressPct: 100,
        score: 33,
        commentCount: 6,
      },
    ],
    reviews: [
      {
        username: "cozylatte",
        dateLabel: "Jun 19, 2026",
        rating: 4.5,
        body: "Career-change slice-of-life with swords in the rearview. Warm, queer-friendly, gently adventurous.",
        spoilers: false,
        likes: 41,
        commentCount: 1,
      },
      {
        username: "needsmoreconflict",
        dateLabel: "Mar 7, 2026",
        rating: 3,
        body: "Lovely vibe; thin plot. Ideal as a palate cleanser, not a main course.",
        spoilers: false,
        likes: 12,
        commentCount: 2,
      },
    ],
  },
  "jonathan-strange": {
    forum: [
      {
        username: "mrnorrellfan",
        title: "Practical magic returns to England",
        body: "Footnotes forever. Norrell’s caution vs Strange’s daring—rival magicians already delicious.",
        spoilers: false,
        progressPct: 8,
        score: 22,
        commentCount: 5,
      },
      {
        username: "faerieroads",
        title: "Napoleonic wars + Faerie",
        body: "Historical fantasy with real bite. The Gentleman with the Thistle-Down Hair chapters unsettle beautifully.",
        spoilers: false,
        progressPct: 55,
        score: 27,
        commentCount: 8,
      },
      {
        username: "longbookclub",
        title: "Worth the doorstopper",
        body: "Pacing is leisurely on purpose. The cost of power and the fate of Lady Pole lingered for weeks.",
        spoilers: true,
        progressPct: 100,
        score: 35,
        commentCount: 12,
      },
    ],
    reviews: [
      {
        username: "footnoteaddict",
        dateLabel: "May 11, 2026",
        rating: 5,
        body: "An alternate Regency where magic reshapes history. Rivalry, Faerie, scholarship, and dread. A modern classic.",
        spoilers: false,
        likes: 43,
        commentCount: 2,
      },
      {
        username: "toodry",
        dateLabel: "Aug 8, 2025",
        rating: 3,
        body: "Brilliant world; patience required. If you bounce off the tone early, you may not recover—and that’s okay.",
        spoilers: false,
        likes: 11,
        commentCount: 1,
      },
    ],
  },
  iewu: {
    forum: [
      {
        username: "lilybloom",
        title: "Ryle enters the chat",
        body: "Neurosurgeon meet-cute with warning lights already flashing. Hoover does emotional intensity—brace.",
        spoilers: false,
        progressPct: 10,
        score: 18,
        commentCount: 9,
      },
      {
        username: "cyclename",
        title: "Hard to keep reading / hard to stop",
        body: "Domestic abuse portrayed in a way that’s triggering and debated. Take care of yourself; skip if you need to.",
        spoilers: false,
        progressPct: 50,
        score: 24,
        commentCount: 31,
      },
      {
        username: "atlasmention",
        title: "That ending choice",
        body: "Divisive on purpose. Some find empowerment; some find the messaging muddled. Book club fuel either way.",
        spoilers: true,
        progressPct: 100,
        score: 29,
        commentCount: 40,
      },
    ],
    reviews: [
      {
        username: "contemporaryfan",
        dateLabel: "Apr 29, 2026",
        rating: 4,
        body: "Emotional, propulsive, and centered on breaking cycles of abuse. Not subtle—but it made me feel everything.",
        spoilers: false,
        likes: 33,
        commentCount: 5,
      },
      {
        username: "criticalread",
        dateLabel: "Oct 5, 2025",
        rating: 2,
        body: "Problematic framing for me around abuse and romance tropes. Others disagree—read reviews carefully first.",
        spoilers: false,
        likes: 27,
        commentCount: 12,
      },
    ],
  },
  atlas: {
    forum: [
      {
        username: "medeiansix",
        title: "Initiation year begins",
        body: "Six powerful candidates, one deadly society, five leave with memories. Dark academia competition unlocked.",
        spoilers: false,
        progressPct: 5,
        score: 35,
        commentCount: 10,
      },
      {
        username: "libbymora",
        title: "Ensemble chaos",
        body: "Everyone is brilliant and terrible. Alliances shifting every chapter. TikTok made me do this and I’m not mad.",
        spoilers: false,
        progressPct: 50,
        score: 28,
        commentCount: 16,
      },
      {
        username: "societyarchives",
        title: "Who survives?",
        body: "Twisty, talky, morally gray. Ending sets the sequel bait hard. Dialectic duels forever.",
        spoilers: true,
        progressPct: 100,
        score: 42,
        commentCount: 19,
      },
    ],
    reviews: [
      {
        username: "darkacademiadaily",
        dateLabel: "Aug 1, 2026",
        rating: 4,
        body: "Secret society initiation with deadly stakes and messy desire. Style-forward ensemble fantasy that thrives on tension.",
        spoilers: false,
        likes: 47,
        commentCount: 4,
      },
      {
        username: "wantedmoremagic",
        dateLabel: "Dec 18, 2025",
        rating: 3,
        body: "Great vibes; characterization uneven and very dialogue-heavy. Fun if you want aesthetic intrigue over tight plot.",
        spoilers: false,
        likes: 21,
        commentCount: 3,
      },
    ],
  },
};

export function getBookSocial(bookId: string): {
  forum: ForumPost[];
  reviews: CommunityReview[];
} {
  const raw = RAW[bookId];
  if (!raw) return fallbackSocial(bookId);
  return pack(bookId, raw);
}
