/** Popular tropes per catalog book — drawn from common reader/critical framing
 * (TV Tropes, Trope Trove, BookTok/romance guides, publisher positioning).
 * Labels use reader-facing language; keep them stable for matching across books.
 */

export const BOOK_TROPES: Record<string, string[]> = {
  "night-circus": ["Star-crossed lovers", "Magical competition", "Circus of magic"],
  "starless-sea": ["Hidden magical world", "Magical library", "Stories within stories"],
  piranesi: ["Ontological mystery", "Infinite labyrinth", "Unreliable memory"],
  "six-crows": ["Heist / caper", "Found family (crew)", "Morally gray protagonists"],
  achilles: ["Myth retelling", "Tragic queer romance", "Slow burn"],
  circe: ["Myth retelling", "Exile & isolation", "Witch reclaiming power"],
  mexico: ["Gothic mansion", "Slow-burn horror", "Haunted house"],
  "ninth-house": ["Dark academia", "Secret societies", "Occult mystery"],
  "ink-blood": ["Magical books", "Estranged sisters", "Hidden magical world"],
  "sea-tranquility": ["Time travel", "Pandemic narrative", "Interconnected lives"],
  bunny: ["Dark academia satire", "Cultish clique", "Surreal horror"],
  hamnet: ["Grief narrative", "Historical fiction", "Family & plague"],
  babel: ["Dark academia", "Colonialism & empire", "Found cohort"],
  yellowface: ["Unreliable narrator", "Literary theft", "Publishing satire"],
  "fourth-wing": ["Enemies to lovers", "Dragon riders", "Forced proximity"],
  tomorrow: ["Creative partnership", "Friends across decades", "Found family of two"],
  "lessons-chemistry": ["Feminist historical", "Fish out of water", "Single parent"],
  "project-hail": ["First contact", "Science problem-solving", "Unlikely friendship"],
  "silent-patient": ["Unreliable narrator", "Psychological thriller", "Obsession"],
  "night-film": ["Conspiracy thriller", "Cult filmmaker mystery", "Labyrinthine investigation"],
  "house-sky": ["Found family", "Magical orphanage", "Cozy fantasy"],
  "a-little-life": ["Found family (friends)", "Trauma narrative", "Queer literary fiction"],
  "thursday-murder": ["Cozy mystery", "Amateur sleuths", "Retirement community"],
  "normal-people": ["Will-they-won't-they", "Class difference", "Coming of age"],
  hobbit: ["Reluctant hero", "Unexpected quest", "Dragon & treasure"],
  acomaf: ["Fated mates", "Slow burn", "Court intrigue"],
  "evelyn-hugo": ["Forbidden / closeted love", "Hollywood glamour", "Confession narrative"],
  "legends-lattes": ["Cozy fantasy", "Found family", "Career change slice-of-life"],
  "jonathan-strange": ["Rival magicians", "Historical fantasy", "Faerie"],
  iewu: ["Domestic abuse cycle", "Contemporary romance", "Trauma & recovery"],
  atlas: ["Dark academia", "Secret society initiation", "Deadly competition"],
  // Expansion — fiction
  "beach-read": ["Enemies to lovers", "Writers in love", "Summer forced proximity"],
  "people-vacation": ["Friends to lovers", "Second chance", "Travel romance"],
  "book-lovers": ["Enemies to lovers", "Bookish romance", "Small town"],
  "funny-story": ["Fake dating", "Roommate romance", "Second chance"],
  "love-hypothesis": ["Fake dating", "STEM romance", "Grumpy/sunshine"],
  "red-white-royal": ["Forbidden romance", "Fake dating", "Queer rom-com"],
  "seven-year-slip": ["Time slip", "Grief & second chances", "Magical apartment"],
  "gone-girl": ["Unreliable narrator", "Marriage thriller", "Media circus"],
  verity: ["Found manuscript", "Dark romance thriller", "Unreliable narrator"],
  "guest-list": ["Wedding murder", "Multiple POVs", "Isolated island"],
  maid: ["Amateur sleuth", "Neurodivergent heroine", "Hotel mystery"],
  "last-thing": ["Missing spouse", "Stepmother bond", "Identity mystery"],
  "sharp-objects": ["Gothic hometown return", "Family secrets", "Unreliable memory"],
  "only-good-indians": ["Indigenous horror", "Guilt & consequence", "Supernatural revenge"],
  "haunting-hill": ["Haunted house", "Psychological horror", "Classic gothic"],
  "blackened-teeth": ["Folk horror", "Wedding gone wrong", "Haunted mansion"],
  dune: ["Chosen one", "Desert planet politics", "Ecological epic"],
  "three-body": ["First contact", "Hard sci-fi mystery", "Civilization stakes"],
  martian: ["Survival problem-solving", "Humor in crisis", "Space isolation"],
  "klara-sun": ["AI narrator", "What makes us human", "Quiet speculative"],
  "ready-player": ["Virtual world quest", "Nerd nostalgia", "Underdog contest"],
  recursion: ["Time / memory thriller", "Grief narrative", "Mind-bending plot"],
  mistborn: ["Heist / revolution", "Magic metal system", "Underdog heroine"],
  "name-wind": ["Frame story", "Legendary hero origin", "University of magic"],
  "gideon-ninth": ["Lesbian necromancers", "Murder mystery contest", "Banter & bones"],
  "poppy-war": ["Military fantasy", "Dark chosen one", "War & empire"],
  "cruel-prince": ["Enemies to lovers", "Faerie court intrigue", "Human in Faerie"],
  acotar: ["Beauty and the beast", "Fae romance", "Deadly bargain"],
  "throne-glass": ["Assassin heroine", "Deadly competition", "Court intrigue"],
  "iron-flame": ["Dragon riders", "War college secrets", "Slow-burn romance"],
  neverwhere: ["Urban fantasy London", "Ordinary to extraordinary", "Hidden city"],
  "american-gods": ["Old gods vs new", "Road trip mythic", "Belief as power"],
  "priory-orange": ["Epic standalone", "Queens & dragons", "East/West politics"],
  "midnight-library": ["What if lives", "Depression & hope", "Philosophical fable"],
  "where-crawdads": ["Marsh setting", "Coming of age", "Murder mystery"],
  "demon-copperhead": ["Modern Dickens", "Appalachia & opioids", "Coming of age"],
  trust: ["Nested narratives", "Wealth & power", "Who tells the story"],
  "vanishing-half": ["Passing & identity", "Twin sisters", "Multi-generational"],
  "little-fires": ["Motherhood & class", "Suburban secrets", "Nature vs nurture"],
  pachinko: ["Multi-generational saga", "Korean diaspora", "Historical epic"],
  "daisy-jones": ["Oral history format", "1970s rock band", "Fame & self-destruction"],
  "malibu-rising": ["One legendary night", "Sibling dynamics", "Famous family"],
  "before-coffee": ["Time travel café", "Second chances", "Gentle magical realism"],
  "convenience-store": ["Social conformity", "Quirky heroine", "Slice of life satire"],
  handmaids: ["Dystopian theocracy", "Feminist classic", "Surveillance state"],
  "1984": ["Totalitarian dystopia", "Thoughtcrime", "Classic warning"],
  "pride-prejudice": ["Enemies to lovers", "Class & manners", "Witty banter"],
  beloved: ["Hauntings of slavery", "Motherhood & trauma", "Literary classic"],
  "lincoln-highway": ["Road trip adventure", "1950s America", "Found family of misfits"],
  "ministry-time": ["Time-travel bureaucracy", "Slow-burn romance", "Spy craft"],
  // Expansion — nonfiction
  educated: ["Coming-of-age memoir", "Family & belief", "Education as escape"],
  "atomic-habits": ["Tiny habit changes", "Systems over goals", "Practical self-improvement"],
  sapiens: ["Big-history survey", "Shared myths", "Human cooperation"],
  "thinking-fast": ["Cognitive bias", "Dual-process mind", "Decision science"],
  becoming: ["Political memoir", "Identity & public life", "Family roots"],
  "born-crime": ["Coming-of-age memoir", "Comedy & hardship", "Apartheid childhood"],
  "into-wild": ["Wilderness adventure", "Idealism & risk", "True biography"],
  "immortal-life": ["Medical ethics", "Scientific discovery", "Family justice"],
  quiet: ["Introvert advocacy", "Culture of personality", "Quiet strength"],
  "bad-blood": ["Startup fraud", "Investigative journalism", "Silicon Valley cautionary"],
  "crying-hmart": ["Grief memoir", "Food & identity", "Mother-daughter"],
  "body-keeps-score": ["Trauma science", "Mind-body healing", "Clinical insights"],
  "mans-search": ["Holocaust testimony", "Meaning & survival", "Logotherapy"],
  "night-wiesel": ["Holocaust testimony", "Faith under atrocity", "Witness literature"],
  "killers-flower": ["True crime history", "Osage murders", "Early FBI"],
  "the-wager": ["Shipwreck survival", "Empire & narrative", "Historical adventure"],
  "say-nothing": ["The Troubles", "True crime history", "Silence & memory"],
  "empire-pain": ["Opioid crisis", "Family dynasty exposé", "Corporate accountability"],
  "between-world": ["Letter to a son", "Race in America", "Essay memoir"],
  "maybe-talk": ["Therapist as patient", "Therapy stories", "Healing & humor"],
  "deep-work": ["Focus as skill", "Distraction economy", "Productivity systems"],
  range: ["Generalists vs specialists", "Career exploration", "Learning science"],
};

export function getBookTropes(bookId: string): string[] {
  return BOOK_TROPES[bookId] ?? [];
}

export function getBooksWithTrope(
  trope: string,
  excludeBookId?: string,
): string[] {
  return Object.entries(BOOK_TROPES)
    .filter(([id, tropes]) => tropes.includes(trope) && id !== excludeBookId)
    .map(([id]) => id);
}
